Description of adj_to_elist
Home > mtids > subfunctions > interface2Simulink > adj_to_elist.m
adj_to_elist
PURPOSE
ADJ_TO_ELIST Reshapes an (N x N) adjacency matrix into a (M x 2) edge list
SYNOPSIS
function elist = adj_to_elist(A)
DESCRIPTION
ADJ_TO_ELIST Reshapes an (N x N) adjacency matrix into a (M x 2) edge list
 This function takes an adjacency matrix as input and outputs an edge list
 INPUTS: A         -- Symmetric adjacency matrix (N x N)
 OUTPUT: elist     -- Edge list (M x 2)
 Authors: Francisco Llobet, Jose Rivera
 Editor: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
 Project: MTIDS (http://code.google.com/p/mtids/)
 Created: 30/5/2011
CROSS-REFERENCE INFORMATION
This function calls:
ne ne(g) --- number of edges in g
nv nv(g) --- number of vertices in g
size size(g) --- returns [nv,ne] for the graph
ne ne(p,q) --- p ~= q checks if p and q are different
nv nv(p) --- number of vertices (elements) of a partition
size size(p) --- returns [nv,np]: number of vertices, parts.
ne test if p ~= q
This function is called by:
export_as_matrix EXPORT_AS_MATRIX gui to export a graph in mtids as a matrix
any_matrix_to_elist ANY_MATRIX_TO_ELIST Reshapes an adjacency matrix into an edge list
SOURCE CODE
function elist = adj_to_elist(A)
%ADJ_TO_ELIST Reshapes an (N x N) adjacency matrix into a (M x 2) edge list
%
% This function takes an adjacency matrix as input and outputs an edge list
%
% INPUTS: A         -- Symmetric adjacency matrix (N x N)
%
% OUTPUT: elist     -- Edge list (M x 2)
%
%
% Authors: Francisco Llobet, Jose Rivera
% Editor: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
% Project: MTIDS (http://code.google.com/p/mtids/)
% Created: 30/5/2011
nv = size(A,1);
ne = 0;
for i=1:nv
   for j=i:nv
      if A(i,j)
          ne = ne + 1;
          elist(ne ,1) = i; %#ok<*AGROW>
          elist(ne ,2) = j;
          A(j,i) = 0;
      end
   end
end
if ne == 0
   elist = 0;
end