Description of blockCanvas
Home > mtids > subfunctions > interface2Simulink > blockCanvas.m
blockCanvas
PURPOSE
blockVanvas.m, defines simulink define Block position
SYNOPSIS
function canvas= blockCanvas(pos)
DESCRIPTION
 blockVanvas.m, defines simulink  define Block position
 plane divided into blocks
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
buildSubsystem buildSubsystem.m
exportLayer exportLayer.m
exportLayer2 exportLayer.m
exportSimulink exportSimulink.m
exportSimulink2 EXPORTSIMULINK2 creates Simulink system out of MTIDS graph
templateModify buildSubsystem.m
templateModify2 TEMPLATEMODIFY2 adapts the template according to given input
SOURCE CODE
% blockVanvas.m, defines simulink  define Block position
% plane divided into blocks
function canvas= blockCanvas(pos)
% set up width and height of Block
width=30;
height=30;
x=pos(1);
y=pos(2);
% coordinates for canvas
upLeftX= x*width ;
upRightX= (x+1)*width ;
loLeftY=y*height;
loRightY= (y+1)*height ;
canvas = [upLeftX loLeftY upRightX loRightY] ;