Description of blockPos
Home > mtids > subfunctions > interface2Simulink > blockPos.m
blockPos
PURPOSE
blockPosition.m
SYNOPSIS
function pos = blockPos(canvas)
DESCRIPTION
 blockPosition.m
 get x,y of block canvas
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
buildSubsystem buildSubsystem.m
importSimulink importSimulink.m :
templateModify buildSubsystem.m
templateModify2 TEMPLATEMODIFY2 adapts the template according to given input
SOURCE CODE
% blockPosition.m
% get x,y of block canvas
function pos = blockPos(canvas)
% set up width and height of Block
width=30;
height=30;
pos(1)=canvas(1)/width ;
pos(2)=canvas(2)/height;