Description of exportSimulink
Home > mtids > subfunctions > interface2Simulink > exportSimulink.m
exportSimulink
PURPOSE
exportSimulink.m
SYNOPSIS
function[] =exportSimulink(name,template,templateList,A, xy, labs)
DESCRIPTION
 exportSimulink.m
 Project: MTIDS
 Created: 27/5/2011
                      inputs: -name: mname of model that will be produced
                              -template: template used to generate subsystems
                              - templateList: List of templates that are
                                 availible in mtids
                              -A: Adjacense matrix,
                              -xy: Position of the nodes
                              -labs: cell with the names of the nodes
                      output: no output, produces a simulink model save manually !!
 This function takes the data produced in mtids and generates an interconnected
 dynamical system in simulink. The system is generated as a circle formation.
CROSS-REFERENCE INFORMATION
This function calls:
blockCanvas blockVanvas.m, defines simulink define Block position
templateModify buildSubsystem.m
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
mtids MTIDS Version 1.2
SOURCE CODE
function[] =exportSimulink(name,template,templateList,A, xy, labs)
% exportSimulink.m
%
% Project: MTIDS
% Created: 27/5/2011
%
%                      inputs: -name: mname of model that will be produced
%                              -template: template used to generate subsystems
%                              - templateList: List of templates that are
%                                 availible in mtids
%                              -A: Adjacense matrix,
%                              -xy: Position of the nodes
%                              -labs: cell with the names of the nodes
%
%                      output: no output, produces a simulink model save manually !!
%
% This function takes the data produced in mtids and generates an interconnected
% dynamical system in simulink. The system is generated as a circle formation.
%% options
vizMaxNodeNumber=50;    % maximal number of nodes where Simulink opens
%% Create the model
try
    sys = name;
new_system(sys)
catch  % if subsystem already exist then look for an availible name
    for i=1:100
        newsys= [sys num2str(i)];
        try
          new_system(newsys) ;
          sys=newsys;
          break;
       catch
       end
    end
end
%% open template and modify it do not visulize if number of nodes to high
nodeNumber= size(A,1);
for i=1:size(templateList,1)
    if any(strcmp(templateList{i},template))
    templateModify(nodeNumber,templateList{i})
    end
end
%% Arrange Subsystems and build them accourding to template
x=xy(:,1);
y=xy(:,2);
nodePosRadius= sqrt(x(1)^2 + y(1)^2) + nodeNumber/2;
graphCenter= [nodePosRadius+4 nodePosRadius+2] ;
for i=1:nodeNumber
    if x(i)>0
    nodePosAngle= atan(-y(i)/x(i)) ;
    else
      nodePosAngle= atan(-y(i)/x(i)) + pi ;
    end
   nodePos= graphCenter + [nodePosRadius*cos(nodePosAngle) nodePosRadius*sin(nodePosAngle)] ;
add_block('built-in/Subsystem',[sys ['/' labs{i}]] , 'position', blockCanvas(nodePos));
%modify template of subsystem call a function
Simulink.BlockDiagram.copyContentsToSubSystem(template{i}, [sys ['/' labs{i}]]);
%close template
end
for i=1:size(templateList,1)
close_system(templateList{i},0)
end
%% Connect Subsystems
for i=1:nodeNumber
    for j=1:nodeNumber
    %if i~=j  % make all nodes connect
    if A(i,j)~=0
   %add_line(sys,[labs{i} '/1'], [labs{j} '/' num2str(i)],'autorouting','on')
    add_line(sys,[labs{i} '/1'], [labs{j} '/' num2str(i)])
    end
    end
end
%% open system
% NO VISULAISATION FOR LARGE NUMBER OF NODES
if(nodeNumber<=vizMaxNodeNumber)
open_system(sys)
end
%% save model ....if model exist the whole thing gives an error (need unique name for model)
if(nodeNumber>vizMaxNodeNumber)
 [filename, pathname] = uiputfile( ...
{'*.mdl','Simulink Model (*.mdl)';
   '*.*',  'All Files (*.*)'}, ...
   'Save model');
 %file = strcat(pathname, filename);
try
save_system(sys,filename);
catch
   close_system(sys,0)
end
close_system(sys,0)
end