Description of matrix_to_string
Home > mtids > subfunctions > interface2Simulink > matrix_to_string.m
matrix_to_string
PURPOSE
SYNOPSIS
function A_str = matrix_to_string(A)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
edit_node EDIT_NODE gui to edit settings of a specific node in a MTIDS graph
create_ss_model
SOURCE CODE
function A_str = matrix_to_string(A)
[ny,nx] = size(A);
A_str = '[ ';
for i=1:ny
    for j=1:nx
        A_str = strcat(A_str,num2str(A(i,j)));
        if (j < nx)
         A_str = strcat(A_str,',');
        elseif i < ny
         A_str = strcat(A_str,';');
        end
        end
end
A_str = strcat(A_str, ']');