Description of array
Home > mtids > subfunctions > matgraph > @permutation > array.m
array
PURPOSE
array(p) --- return p as an array
SYNOPSIS
function a = array(p)
DESCRIPTION
 array(p) --- return p as an array
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
cayley cayley(g,perms) -- create a Cayley graph (undirected)
edge_color edge_color(g,algo) --- find a proper edge coloring of the graph g
renumber renumber the vertices of a graph
save save(g,filename) --- save a graph to disk
inv inv(p) returns the inverse permutation of p
miss miss(p) -- maximum increasing subsequence
perm % Permutations in Matgraph
SOURCE CODE
function a = array(p)
% array(p) --- return p as an array
a = p.array;