Description of permutation
Home > mtids > subfunctions > matgraph > @permutation > permutation.m
permutation
PURPOSE
constructor for the permutation class
SYNOPSIS
function p = permutation(n)
DESCRIPTION
 constructor for the permutation class
 p = permutation(n) --- create a new (identity) permutation on 1:n
 p = permutation(vec) --- create a new permutation based on the array vec
 (which should be a permutation of 1:n).
CROSS-REFERENCE INFORMATION
This function calls:
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
cayley cayley(g,perms) -- create a Cayley graph (undirected)
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
iso [yn,p] = iso(g,h) --- is g isomorphic to h?
renumber renumber the vertices of a graph
inv inv(p) returns the inverse permutation of p
mpower p^t is p multiplied by itself t times. May have t <= 0.
mtimes p*q is the composition of p and q
randomMATGRAPH random(p) --- return a random reordering of the elements of p
cayley_graph % Creating a Cayley graph
isomorphism % Checking graph isormorphism in Matgraph
perm % Permutations in Matgraph
swap swap(a,b) -- return a permutation that swaps a and b, i.e., (a,b)
SOURCE CODE
function p = permutation(n)
% constructor for the permutation class
% p = permutation(n) --- create a new (identity) permutation on 1:n
% p = permutation(vec) --- create a new permutation based on the array vec
% (which should be a permutation of 1:n).
if nargin==0
    n = 1;
end
bad = 'Input invalid: must be a permutation of 1:n or a single integer';
[r,c] = size(n);
if (r>1) && (c>1)
    error(bad);
end
if (r==1) && (c==1)
    x = 1:n;
else
    x = n;
end
x = x(:)';
n = length(x);
y = sort(x);
if any(y ~= 1:n)
    error(bad);
end
p.array = x;
p = class(p,'permutation');