Description of parts
Home > mtids > subfunctions > matgraph > @partition > parts.m
parts
PURPOSE
parts(p) --- returns the parts of p in a cell array
SYNOPSIS
function cells = parts(p)
DESCRIPTION
 parts(p) --- returns the parts of p in a cell array
CROSS-REFERENCE INFORMATION
This function calls:
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
bipartition part = bipartition(g) --- find bipartition of a bipartite graph
bipmatch bipmatch --- maximum matching in a bipartite graph
cdraw cdraw(g,dir,coloring) -- draw g with a given vertex coloring
color color(g,algo) --- color the graph g by a given algorithm
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
iso [yn,p] = iso(g,h) --- is g isomorphic to h?
renumber renumber the vertices of a graph
array array(p) --- return a single array showing the part numbers of elements.
partn % Partitions in Matgraph
SOURCE CODE
function cells = parts(p)
% parts(p) --- returns the parts of p in a cell array
[m,n] = size(p.array);
cells = cell(1,m);
for k=1:m
    cells{k} = find(p.array(m+1-k,:));
end