Description of edraw
Home > mtids > subfunctions > matgraph > samples > edraw.m
edraw
PURPOSE
SYNOPSIS
function edraw(g,elist)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
draw draw(g) --- draw g in a figure window
embed embed --- create an embedding for a graph
free free(g) --- free the graph from the system
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
graph graph: constructor for the graph class
nv nv(g) --- number of vertices in g
draw draw(g) --- draw g in a figure window
nv nv(p) --- number of vertices (elements) of a partition
This function is called by:
matching % Matchings in bipartite graphs
SOURCE CODE
function edraw(g,elist)
n = nv(g);
h = graph(n);       % create a graph with same number of vertices as g
add(h,elist);       % add edges in elist to h
embed(h, getxy(g)); % copy g's embedding
draw(g,':');        % draw g with dotted lines
draw(h);            % overdraw h with solid lines
free(h);            % release h