Description of eulerian
Home > mtids > subfunctions > matgraph > samples > eulerian.m
eulerian
PURPOSE
% Eulerian tours
SYNOPSIS
This is a script file.
DESCRIPTION
% Eulerian tours
 The |euler_trail| function finds Eulerian trails and tours in graphs.
% Line graph of the Petersen graph
 The Petersen graph has no Eulerian trail or tour, but its line graph
 does. The Eulerian trail is reported as a list of edges.
CROSS-REFERENCE INFORMATION
This function calls:
cube cube(g,k) --- create a k-cube (default k = 3)
delete delete --- delete vertices or edges from a graph
distxy distxy(g) -- give g a distance based embedding
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
free free(g) --- free the graph from the system
graph graph: constructor for the graph class
line_graph line_graph(g,h) --- set g to be the line graph of h
ndraw ndraw(g) --- draw g in a figure window with numbered vertices
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
petersen petersen(g) --- overwrite g with the Petersen graph
This function is called by:
SOURCE CODE
%% Eulerian tours
% The |euler_trail| function finds Eulerian trails and tours in graphs.
%% Line graph of the Petersen graph
% The Petersen graph has no Eulerian trail or tour, but its line graph
% does. The Eulerian trail is reported as a list of edges.
g = graph;
petersen(g);
h = graph;
line_graph(h,g);
distxy(h);
clf;ndraw(h);
euler_trail(h)
%% 4-cube minus an edge
% The four dimensional cube is a 4-regular graph. Deleting one edge from
% this graph leaves a connected graph with exactly two vertices of odd
% degree. We find an Euler trail in that graph.
k = graph;
cube(k,4);
distxy(k);
delete(k,1,2);
euler_trail(k)
clf;ndraw(k)
%% Release storage
free(g); free(h); free(k);