Description of splitter
Home > mtids > subfunctions > matgraph > samples > splitter.m
splitter
PURPOSE
% Splitting the vertex set of a graph
SYNOPSIS
This is a script file.
DESCRIPTION
% Splitting the vertex set of a graph
 We demonstrate how to split the vertex set of a graph into two parts
 using the |split| method. The goal is to separate the vertices of the
 graph into two natural clusters. The splitting is based on the Fiedler
 vector of the Laplacian matrix.
% Create a random tree
CROSS-REFERENCE INFORMATION
This function calls:
cdraw cdraw(g,dir,coloring) -- draw g with a given vertex coloring
distxy distxy(g) -- give g a distance based embedding
free free(g) --- free the graph from the system
graph graph: constructor for the graph class
grid grid(g,a,b) --- create an a-by-b grid graph
random_tree random_tree(t,n) --- overwrite t with a random tree on n vertices
split part = split(g) --- partition the vertices of g into two subsets
This function is called by:
SOURCE CODE
%% Splitting the vertex set of a graph
% We demonstrate how to split the vertex set of a graph into two parts
% using the |split| method. The goal is to separate the vertices of the
% graph into two natural clusters. The splitting is based on the Fiedler
% vector of the Laplacian matrix.
%% Create a random tree
g = graph;
random_tree(g,25);
%% Find an embedding for the tree
% Note: This requires the Optimization Toolbox
distxy(g);
%% Partition the vertices
p = split(g)
%% Draw the result
cdraw(g,p);
%% Partition a grid graph
grid(g,3,11);
p = split(g);
clf; % erase the previous drawing
cdraw(g,p)
%% Release storage
free(g);