% text('Interpreter','latex',...
%    'String','Hallo$$\int_0^x\!\int_y dF(u,v)$$',...
%    'Position',[.5 .5],...
%    'FontSize',16);
% axis off; 
% \\The number of independent subgraphs that are not connected to each other.\\
% f=figure
% %uicontrols can't display latex:
% u=uicontrol('units','pixels','position',[20 200 200 24],...
%     'style','text','string','I can''t display \pi',...
%     'horiz','left',...
%     'backgroundcolor',get(f,'color'));

%but text objects can:
axes('units','pixels','position',[40 110 30 320],'visible','off')
h1=text(0,0.5,'\underline{Independent Graphs:}\\ ','interpreter','latex',...
    'horiz','left','vert','middle') 


axes('units','pixels','position',[40 110 10 280],'visible','off')
h2=text(0,0.5,'\\The number of independent subgraphs that are not connected to each other.\\ ','interpreter','latex',...
    'horiz','left','vert','middle') 
axes('units','pixels','position',[40 110 10 240],'visible','off')
h3=text(0,0.5,'\\The number of independent subgraphs that are not connected to each other.\\ ','interpreter','latex',...
    'horiz','left','vert','middle') 
axes('units','pixels','position',[40 110 10 200],'visible','off')
h4=text(0,0.5,'\\The number of independent subgraphs that are not connected to each other.\\ ','interpreter','latex',...
    'horiz','left','vert','middle') 
axes('units','pixels','position',[40 110 10 160],'visible','off')
h5=text(0,0.5,'\\The number of independent subgraphs that are not connected to each other.\\ ','interpreter','latex',...
    'horiz','left','vert','middle') 


axes('units','pixels','position',[40 110 20 120],'visible','off')
h6=text(0,0.5,'\\The number of independent subgraphs that are not connected to each other.\\ ','interpreter','latex',...
    'horiz','left','vert','middle') 
axes('units','pixels','position',[40 110 20 80],'visible','off')
h7=text(0,0.5,'\\The number of independent subgraphs that are not connected to each other.\\ ','interpreter','latex',...
    'horiz','left','vert','middle') 
axes('units','pixels','position',[40 110 20 40],'visible','off')
h8=text(0,0.5,'\\The number of independent subgraphs that are not connected to each other.\\ ','interpreter','latex',...
    'horiz','left','vert','middle') 

axes('units','pixels','position',[40 110 20 1],'visible','off')
h9=text(0,0.5,'\\The number of independent subgraphs that are not connected to each other.\\ ','interpreter','latex',...
    'horiz','left','vert','middle') 
