Description of find_row
Home > mtids > subfunctions > matgraph > @graph > private > find_row.m
find_row
PURPOSE
find_row(r,M)
SYNOPSIS
function idx = find_row(r, M, a, b)
DESCRIPTION
 find_row(r,M)
 find row r in matrix M. Assume rows of M are sorted and unique
 find_row(r,M,a,b)
 a = lowest row to check (default 1)
 b = highest row to check (default number of rows in M)
 return the idx of the row, or 0 if not found
CROSS-REFERENCE INFORMATION
This function calls:
find_row find_row(r,M)
vector_compare vector_compare(v,w) -- lexicographically compare row vectors
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
cayley cayley(g,perms) -- create a Cayley graph (undirected)
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
find_row find_row(r,M)
SOURCE CODE
function idx = find_row(r, M, a, b)
% find_row(r,M)
% find row r in matrix M. Assume rows of M are sorted and unique
%
% find_row(r,M,a,b)
% a = lowest row to check (default 1)
% b = highest row to check (default number of rows in M)
%
% return the idx of the row, or 0 if not found
if nargin < 3
    a = 1;
    b = size(M,1);
end
if a>b
    idx = 0;
    return
end
if a==b
    if vector_compare(r,M(a,:)) == 0
        idx = a;
    else
        idx = 0;
    end
    return
end
mid = floor((a+b)/2);
sg = vector_compare(r, M(mid,:));
switch sg
    case 0,
        idx = mid;
        return;
    case -1,
        idx = find_row(r, M, a, mid-1);
        return
    case 1,
        idx = find_row(r, M, mid+1, b);
end