Description of q_init
Home > mtids > subfunctions > matgraph > @graph > private > q_init.m
q_init
PURPOSE
q_init(n) --- initialize private queue with capacity n
SYNOPSIS
function q_init(n)
DESCRIPTION
 q_init(n) --- initialize private queue with capacity n
 The queue supports the following modifying operations
 q_push: add an element to the end of the queue
 q_pop_front: pop an element from the front of the queue
 q_pop_back: pop an element from the end of the queue
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bfstree bfstree(t,g,v) --- create a breadth-first spanning tree of g
dfstree dfstree(t,g,v) --- create a depth-first spanning tree of g
find_path find_path(g,u,v) --- find a shortest path from u to v
SOURCE CODE
function q_init(n)
% q_init(n) --- initialize private queue with capacity n
% The queue supports the following modifying operations
% q_push: add an element to the end of the queue
% q_pop_front: pop an element from the front of the queue
% q_pop_back: pop an element from the end of the queue
global GRAPH_MAGIC
GRAPH_MAGIC.Q.array = zeros(n,1);
GRAPH_MAGIC.Q.first = 1;
GRAPH_MAGIC.Q.last = 0;