Description of domination
Home > mtids > subfunctions > matgraph > samples > domination.m
domination
PURPOSE
% Domination in graphs
SYNOPSIS
This is a script file.
DESCRIPTION
% Domination in graphs
 We demonstrate how to find a minimum dominating set in a graph. This requires
 Matlab's Optimization Toolbox. We illustrate this using Petersen's graph
 and a grid graph.
% Petersen's graph example
CROSS-REFERENCE INFORMATION
This function calls:
cdraw cdraw(g,dir,coloring) -- draw g with a given vertex coloring
dom [d,S] = dom(g) --- domination number of g
free free(g) --- free the graph from the system
graph graph: constructor for the graph class
grid grid(g,a,b) --- create an a-by-b grid graph
nv nv(g) --- number of vertices in g
petersen petersen(g) --- overwrite g with the Petersen graph
nv nv(p) --- number of vertices (elements) of a partition
partition partition --- constructor for the partition class
This function is called by:
SOURCE CODE
%% Domination in graphs
% We demonstrate how to find a minimum dominating set in a graph. This requires
% Matlab's Optimization Toolbox. We illustrate this using Petersen's graph
% and a grid graph.
%% Petersen's graph example
g = graph;
petersen(g);
[d,S]=dom(g);
disp(['The domination number of the Petersen graph is ', int2str(d)])
notS = setdiff(1:nv(g), S);
p = partition({S,notS});
clf;cdraw(g,p)
%% Grid graph example
grid(g,5,5);
[d,S]=dom(g);
disp(['The domination number of the 5-by-5 grid is ', int2str(d)])
notS = setdiff(1:nv(g), S);
p = partition({S,notS});
clf;cdraw(g,p)
%% Release storage
free(g)