Description of hamiltonian
Home > mtids > subfunctions > matgraph > samples > hamiltonian.m
hamiltonian
PURPOSE
% Finding and displaying Hamiltonian cycles in Matgraph
SYNOPSIS
This is a script file.
DESCRIPTION
% Finding and displaying Hamiltonian cycles in Matgraph
 We illustrate how to find a Hamiltonian cycle in a graph, convert that
 cycle into a subgraph, and then display the results.
% Create a graph and find a Hamiltonian cycle
 For this illustration, we use the dodecahedron graph.
 Note: The dodecahedron graph comes with a built-in embedding. We use this
 embedding later when we draw the graph and its Hamiltonian cycle.
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
dodecahedron dodecahedron(g) --- overwrite g with the dodecahedron graph
draw draw(g) --- draw g in a figure window
embed embed --- create an embedding for a graph
free free(g) --- free the graph from the system
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
graph graph: constructor for the graph class
hamiltonian_cycle hamiltonian_cycle(g) --- find a Hamiltonian cycle in g (if one exists)
nv nv(g) --- number of vertices in g
draw draw(g) --- draw g in a figure window
nv nv(p) --- number of vertices (elements) of a partition
This function is called by:
SOURCE CODE
%% Finding and displaying Hamiltonian cycles in Matgraph
% We illustrate how to find a Hamiltonian cycle in a graph, convert that
% cycle into a subgraph, and then display the results.
%% Create a graph and find a Hamiltonian cycle
% For this illustration, we use the dodecahedron graph.
%
% Note: The dodecahedron graph comes with a built-in embedding. We use this
% embedding later when we draw the graph and its Hamiltonian cycle.
g = graph;
dodecahedron(g);
c = hamiltonian_cycle(g);
disp(c')
%% Convert the list of vertices into a cycle graph
n = nv(g);
h = graph(n);
for k=1:n-1
    add(h,c(k),c(k+1))
end
add(h,c(1),c(n))
%% Copy the embedding of the original graph to the cycle
embed(h, getxy(g))
%% Create the drawing
% We first draw |g| with dotted lines and then overlay the result with |h|
% drawn with solid lines.
draw(g,':')
draw(h)
%% Release graphs
free(g)
free(h)