Description of ramsey
Home > mtids > subfunctions > matgraph > samples > ramsey.m
ramsey
PURPOSE
% Lower bound for the Ramsey number R(4)
SYNOPSIS
This is a script file.
DESCRIPTION
% Lower bound for the Ramsey number R(4)
 We show that the the Ramsey number R(4) is greater than 17 by presenting
 a graph with 17 vertices that has clique and independence numbers equal to
 three. The Matgraph |alpha| and |omega| functions require the
 Optimization Toolbox.
% The Paley graph
 The graph we use is the Paley graph with n=17. The vertices of this graph
 correspond to the integers mod 17 with an edge between two vertices
 exactly when their difference is a quadratic residue mod 17. The |paley|
 function creates such a graph.
CROSS-REFERENCE INFORMATION
This function calls:
alpha [a,S] = alpha(g) --- indepencence number
cdraw cdraw(g,dir,coloring) -- draw g with a given vertex coloring
free free(g) --- free the graph from the system
graph graph: constructor for the graph class
omega [w,S] = omega(g) --- clique number
paley paley(g,n) --- create a Paley graph with n vertices
partition partition --- constructor for the partition class
This function is called by:
SOURCE CODE
%% Lower bound for the Ramsey number R(4)
% We show that the the Ramsey number R(4) is greater than 17 by presenting
% a graph with 17 vertices that has clique and independence numbers equal to
% three. The Matgraph |alpha| and |omega| functions require the
% Optimization Toolbox.
%% The Paley graph
% The graph we use is the Paley graph with n=17. The vertices of this graph
% correspond to the integers mod 17 with an edge between two vertices
% exactly when their difference is a quadratic residue mod 17. The |paley|
% function creates such a graph.
g = graph;
paley(g,17);
%% Maximum clique
% We use |omega| to find the clique number and a maximum clique.
[w,S] = omega(g);
disp(['The clique number is ', int2str(w)])
notS = setdiff(1:17,S);
p = partition({S,notS});
clf;cdraw(g,p);
%% Maximum independent set
% We use |alpha| to find the independence number and a maximum independent
% set.
[a,S] = alpha(g);
disp(['The independence number is ', int2str(a)])
notS = setdiff(1:17,S);
p = partition({S,notS});
clf;cdraw(g,p);
%% Release storage
free(g)