Description of spanning_tree
Home > mtids > subfunctions > matgraph > samples > spanning_tree.m
spanning_tree
PURPOSE
% Finding spanning trees
SYNOPSIS
This is a script file.
DESCRIPTION
% Finding spanning trees
 Matgraph provides two functions for finding spanning trees:
 * |bfsptree| --- breadth first spanning tree
 * |dfsptree| --- depth first spanning tree
% Set up the graph
 We illustrate finding spanning trees in the icosahedron graph.
CROSS-REFERENCE INFORMATION
This function calls:
bfstree bfstree(t,g,v) --- create a breadth-first spanning tree of g
dfstree dfstree(t,g,v) --- create a depth-first spanning tree of g
draw draw(g) --- draw g in a figure window
free free(g) --- free the graph from the system
graph graph: constructor for the graph class
icosahedron icosahedron(g) --- overwrite g with the icosahedron graph
nsptrees nsptrees(g) --- number of spanning trees of g.
draw draw(g) --- draw g in a figure window
This function is called by:
SOURCE CODE
%% Finding spanning trees
% Matgraph provides two functions for finding spanning trees:
%
% * |bfsptree| --- breadth first spanning tree
% * |dfsptree| --- depth first spanning tree
%% Set up the graph
% We illustrate finding spanning trees in the icosahedron graph.
g = graph;
icosahedron(g);
%% Depth first spanning tree
t = graph;
dfstree(t,g);
clf; draw(g,':');
draw(t)
%% Breadth first spanning tree
bfstree(t,g);
clf; draw(g,':');
draw(t)
%% Counting spanning trees
% The matrix-tree theorem makes enumerating spanning trees in Matlab
% especially easy.
nt = nsptrees(g);
disp(['The icosahedron graph has ', int2str(nt),' spanning trees']);
%% Release the graphs
free(t)
free(g)