Description of check
Home > mtids > subfunctions > matgraph > @partition > check.m
check
PURPOSE
check(p) --- check that the datastructure holding p is a valid partition
SYNOPSIS
function yn = check(p)
DESCRIPTION
 check(p) --- check that the datastructure holding p is a valid partition
CROSS-REFERENCE INFORMATION
This function calls:
full full(g) --- convert internal storage for g to full
This function is called by:
mtids MTIDS Version 1.2
input_parameter_adaptation_Callback INPUT_PARAMETER_ADAPTATION_CALLBACK automatic correction of numerical parameters
partition partition --- constructor for the partition class
systemConsistencyTest SYSTEMCONSISTENCYTEST compares input signal with input depending parameters
SOURCE CODE
function yn = check(p)
% check(p) --- check that the datastructure holding p is a valid partition
s = full(sum(p.array,1));  % col sums should all be 1
t = full(sum(p.array,2));  % row sums should all be positive
yn = all(s == 1)  & all(t>0);