Description of np
Home > mtids > subfunctions > matgraph > @partition > np.m
np
PURPOSE
np(p) --- number of parts in the partition p
SYNOPSIS
function m = np(p)
DESCRIPTION
 np(p) --- number of parts in the partition p
CROSS-REFERENCE INFORMATION
This function calls:
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
bipartition part = bipartition(g) --- find bipartition of a bipartite graph
cayley cayley(g,perms) -- create a Cayley graph (undirected)
cdraw cdraw(g,dir,coloring) -- draw g with a given vertex coloring
color color(g,algo) --- color the graph g by a given algorithm
components components(g) --- find the components of the graph g
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
hamiltonian_cycle hamiltonian_cycle(g) --- find a Hamiltonian cycle in g (if one exists)
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
iso [yn,p] = iso(g,h) --- is g isomorphic to h?
renumber renumber the vertices of a graph
merge merge(p,x,y) --- form a partition from p by combining x and y's parts.
mtimes mtimes(p,q) --- p*q is the meet of the partitions p and q
eq test if p == q
mtimes p*q is the composition of p and q
coloring % Coloring graphs in Matgraph
SOURCE CODE
function m = np(p)
% np(p) --- number of parts in the partition p
m = size(p.array,1);