Description of size
Home > mtids > subfunctions > matgraph > @partition > size.m
size
PURPOSE
size(p) --- returns [nv,np]: number of vertices, parts.
SYNOPSIS
function s = size(p)
DESCRIPTION
 size(p) --- returns [nv,np]: number of vertices, parts.
CROSS-REFERENCE INFORMATION
This function calls:
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
mtids MTIDS Version 1.2
TextField1InputSpecs_Callback TEXTFIELD1INPUTSPECS_CALLBACK consistency check for user edit field
checkNodeInput CHECKNODEINPUT Tests input signal
edit_node EDIT_NODE gui to edit settings of a specific node in a MTIDS graph
edit_paramValues EDIT_PARAMVALUES gui to edit numerical parameter values of a template
import_dynamic_params IMPORT_DYNAMIC_PARAMS gui for importing tempates to MTIDS
manageParamSets MANAGEPARAMSETS gui for managing templates and its numerical parameter sets
setnodecolor SETNODECOLOR gui to set the appearance of the nodes in MTIDS
getDegree GETDEGREE Computes in- and outdegree of a node in a digraph
getNumericValue GETNUMERICVALUE converts a table element from char to double
get_BlockParams GET_BLOCKPARAMS block and parameter names for predefined block types
get_tableColumnWidth GET_TABLECOLUMNWIDTH estimates width of table
input_parameter_adaptation_Callback INPUT_PARAMETER_ADAPTATION_CALLBACK automatic correction of numerical parameters
adj_to_elist ADJ_TO_ELIST Reshapes an (N x N) adjacency matrix into a (M x 2) edge list
any_matrix_to_elist ANY_MATRIX_TO_ELIST Reshapes an adjacency matrix into an edge list
exportLayer exportLayer.m
exportLayer2 exportLayer.m
exportSimulink exportSimulink.m
exportSimulink2 EXPORTSIMULINK2 creates Simulink system out of MTIDS graph
matrix_to_string
isValidData ISVALIDDATA Test prompted user data for feasiblity
add add --- add edge(s) to the graph
alpha [a,S] = alpha(g) --- indepencence number
cayley cayley(g,perms) -- create a Cayley graph (undirected)
cdraw cdraw(g,dir,coloring) -- draw g with a given vertex coloring
chromatic_poly chrompoly(g) --- find the chromatic polynomial of g
delete delete --- delete vertices or edges from a graph
distxy distxy(g) -- give g a distance based embedding
embed embed --- create an embedding for a graph
eq yn = eq(g,h) --- check if two graphs are equal (identical)
graph graph: constructor for the graph class
hasxy hasxy(g) --- determine if an embedding has been created for g
incidence_matrix incidence_matrix(g) --- return the vertex/edge incidence matrix.
interval_graph interval_graph(g,ilist) --- create an interval graph
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
line_graph line_graph(g,h) --- set g to be the line graph of h
ne ne(g) --- number of edges in g
iso [yn,p] = iso(g,h) --- is g isomorphic to h?
find_row find_row(r,M)
random_planar random_planar(g,n) --- create a random planar triangulation
sgf sgf --- simple graph format: a 2-column matrix representation
sl2graph sl2graph(g,p) -- create an SL(2,p) graph
display display(p) --- used to display paritions to the console
eq eq(p,q) --- p==q checks if two partitions are equal
np np(p) --- number of parts in the partition p
nv nv(p) --- number of vertices (elements) of a partition
parts parts(p) --- returns the parts of p in a cell array
size size(p) --- returns [nv,np]: number of vertices, parts.
subsref subsref --- implements the notation p(v) and p(v,w)
isemptyMATGRAPH isempty(p) --- check if the permutation p is of size 0
permutation constructor for the permutation class
check_matrix check_matrix(A) --- check if A is a valid adjacency matrix for a graph
readImportedTemplates READIMPORTEDTEMPLATES reads Simulink templates out of folder
newTablePosition NEWTABLEPOSITION set new layout position for import_dynamic_params
saveParamSet2File SAVEPARAMSET2FILE storing parameter set for a template
sizeChar2Pixel SIZECHAR2PIXEL conversion of char symbols to pixel size
systemConsistencyTest SYSTEMCONSISTENCYTEST compares input signal with input depending parameters
testingValueSet TESTINGVALUESET checking numerical parameters of template
SOURCE CODE
function s = size(p)
% size(p) --- returns [nv,np]: number of vertices, parts.
[m,n] = size(p.array);
s = [n,m];