Description of computeInputSizes
Home > mtids > subfunctions > computeInputSizes.m
computeInputSizes
PURPOSE
COMPUTEINPUTSIZES Computes signal sizes of nodes inputs
SYNOPSIS
function computeInputSizes(handles)
DESCRIPTION
COMPUTEINPUTSIZES Computes signal sizes of nodes inputs
 This function computes the number of input signals of each node, which is
 a necessary information for linear systems, due to the input signal size
 must be known to set the node parameters correctly.
 INPUT:    (figure) handles
 OUTPUT:   none - node input signal size will be written into node i's
           template, in the field: data.templates{i,2}.nodeInputs
 Author: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
 Project: MTIDS (http://code.google.com/p/mtids/)
CROSS-REFERENCE INFORMATION
This function calls:
checkNodeInput CHECKNODEINPUT Tests input signal
nv nv(g) --- number of vertices in g
nv nv(p) --- number of vertices (elements) of a partition
This function is called by:
mtids MTIDS Version 1.2
SOURCE CODE
function computeInputSizes(handles)
%COMPUTEINPUTSIZES Computes signal sizes of nodes inputs
%
% This function computes the number of input signals of each node, which is
% a necessary information for linear systems, due to the input signal size
% must be known to set the node parameters correctly.
%
% INPUT:    (figure) handles
%
% OUTPUT:   none - node input signal size will be written into node i's
%           template, in the field: data.templates{i,2}.nodeInputs
%
% Author: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
% Project: MTIDS (http://code.google.com/p/mtids/)
data = getappdata(handles.figure1,'appData');
if nv(data.g) == 0
    return
end
for ii = 1:nv(data.g)
    [dontuseA dontuseB temp] = checkNodeInput(ii,data); %#ok<ASGLU>
    data.templates{ii,2}.nodeInputs = temp;
end
setappdata(handles.figure1,'appData',data);