Description of systemConsistencyTest
Home > mtids > subfunctions > systemConsistencyTest.m
systemConsistencyTest
PURPOSE
SYSTEMCONSISTENCYTEST compares input signal with input depending parameters
SYNOPSIS
function varargout = systemConsistencyTest(handles,varargin)
DESCRIPTION
SYSTEMCONSISTENCYTEST compares input signal with input depending parameters
 This function checks the system, consisting of the graph and its
 numerical dynamic parameters, which are hidden inside the node templates,
 for consistency
 INPUT:    (1) -- Handles to parent figure
 OUTPUT:   (1) -- Boolean, '1' for no errors found
           (2) -- Vector containing if node has consistent input depending
                   parameters
 Author: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
 Project: MTIDS (http://code.google.com/p/mtids/)
CROSS-REFERENCE INFORMATION
This function calls:
checkNodeInput CHECKNODEINPUT Tests input signal
nv nv(g) --- number of vertices in g
size size(g) --- returns [nv,ne] for the graph
check check(p) --- check that the datastructure holding p is a valid partition
nv nv(p) --- number of vertices (elements) of a partition
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
mtids MTIDS Version 1.2
input_parameter_adaptation_Callback INPUT_PARAMETER_ADAPTATION_CALLBACK automatic correction of numerical parameters
SOURCE CODE
function varargout = systemConsistencyTest(handles,varargin)
%SYSTEMCONSISTENCYTEST compares input signal with input depending parameters
%
% This function checks the system, consisting of the graph and its
% numerical dynamic parameters, which are hidden inside the node templates,
% for consistency
%
% INPUT:    (1) -- Handles to parent figure
%
% OUTPUT:   (1) -- Boolean, '1' for no errors found
%           (2) -- Vector containing if node has consistent input depending
%                   parameters
%
% Author: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
% Project: MTIDS (http://code.google.com/p/mtids/)
if size(varargin,2) == 1
    plotBadNodes = varargin{1};
else
    plotBadNodes = 1;
end
data = getappdata(handles.figure1,'appData');
if nv(data.g) ~= 0
    isCorrect = zeros( nv(data.g),1 );
    error = cell( nv(data.g),1 );
    for kk = 1:nv(data.g)
       [isCorrect(kk) error{kk}] = checkNodeInput(kk,data);
    end
    if any( ~isCorrect )
        check = 0;
        % Display errors
        if plotBadNodes
            disp('Errors occured for node number...');
            for kk = 1:nv(data.g)
                if ~isCorrect(kk)
                    disp([num2str(kk) ', concerning the variables: ',...
                        error{kk}.DimMismatch   ]);
                end
            end
        end
    else
        check = 1;
    end
else
    check = 0;
    isCorrect = [];
end
varargout{1} = check;
varargout{2} = isCorrect;