Description of getDegree
Home > mtids > subfunctions > getDegree.m
getDegree
PURPOSE
GETDEGREE Computes in- and outdegree of a node in a digraph
SYNOPSIS
function [inDegree,outDegree] = getDegree(matrix)
DESCRIPTION
GETDEGREE Computes in- and outdegree of a node in a digraph
 Computes the in- and out-degree of a adjacency matrix, which represents
 a directed graph.
 INPUT:   matrix    -- Must be an N-by-N matrix with zeros on the diagonal
 OUTPUT:  inDegree  -- A Vector of Size N-by-1, which holds the in degree
                       of each vertex of the graph, which is represented
                       by 'matrix'
          outDegree -- Similar to inDegree, but for the outdegree of each
                       vertex
 Author: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
 Project: MTIDS (http://code.google.com/p/mtids/)
CROSS-REFERENCE INFORMATION
This function calls:
matrix matrix(g) --- return (a copy of) the adjacency matrix of g
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
mtids MTIDS Version 1.2
export_as_matrix EXPORT_AS_MATRIX gui to export a graph in mtids as a matrix
SOURCE CODE
function [inDegree,outDegree] = getDegree(matrix)
%GETDEGREE Computes in- and outdegree of a node in a digraph
%
% Computes the in- and out-degree of a adjacency matrix, which represents
% a directed graph.
%
% INPUT:   matrix    -- Must be an N-by-N matrix with zeros on the diagonal
%
% OUTPUT:  inDegree  -- A Vector of Size N-by-1, which holds the in degree
%                       of each vertex of the graph, which is represented
%                       by 'matrix'
%          outDegree -- Similar to inDegree, but for the outdegree of each
%                       vertex
%
% Author: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
% Project: MTIDS (http://code.google.com/p/mtids/)
n = size(matrix,1);
inDegree = zeros(n,1);
outDegree = zeros(n,1);
for i=1:n
    inDegree(i) = length(find(matrix(:,i)));
    outDegree(i) = length(find(matrix(i,:)));
end
if sum(inDegree) ~= sum(outDegree)
    fprintf('Something went wrong with the computation of the vertex degrees.\n');
    return
end