Description of newTablePosition
Home > mtids > subfunctions > newTablePosition.m
newTablePosition
PURPOSE
NEWTABLEPOSITION set new layout position for import_dynamic_params
SYNOPSIS
function newTablePosition(varargin)
DESCRIPTION
NEWTABLEPOSITION set new layout position for import_dynamic_params
 Computes and sets new layout positions for the figure import_dynamic_params
 INPUT:    (1) -- Struct, containing handles to all elements of parent
                   figure
           (2) -- eventdata
           (3) -- Row names
           (4) -- New data table content
 OUTPUT: (none)
 Author: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
 Project: MTIDS (http://code.google.com/p/mtids/)
CROSS-REFERENCE INFORMATION
This function calls:
figResize FIGRESIZE figure resize function for pp2.fig
get_tableColumnWidth GET_TABLECOLUMNWIDTH estimates width of table
save save(g,filename) --- save a graph to disk
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
sizeChar2Pixel SIZECHAR2PIXEL conversion of char symbols to pixel size
This function is called by:
import_dynamic_params IMPORT_DYNAMIC_PARAMS gui for importing tempates to MTIDS
SOURCE CODE
function newTablePosition(varargin)
%NEWTABLEPOSITION set new layout position for import_dynamic_params
%
% Computes and sets new layout positions for the figure import_dynamic_params
%
% INPUT:    (1) -- Struct, containing handles to all elements of parent
%                   figure
%           (2) -- eventdata
%           (3) -- Row names
%           (4) -- New data table content
%
% OUTPUT: (none)
%
% Author: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
% Project: MTIDS (http://code.google.com/p/mtids/)
if size(varargin,2) < 4
    error('Insufficient number of arguments');
end
handles                 = varargin{1};
eventdata               = varargin{2};
rownames                = varargin{3};
dataNew                 = varargin{4};
figResize(handles.figure1,eventdata,handles);
while 1
    heightTableNew = 1.25*sizeChar2Pixel(handles.figure1, 'h', ( size(dataNew,1) + 2 ) );
    [ widthTableNew columnwidth] = get_tableColumnWidth(handles.figure1,...
        rownames,dataNew,get(handles.t,'ColumnName'));
    positionTable = abs(get(handles.t,'Position'));
    positionTableNew = positionTable;
    positionTableNew(3) = widthTableNew;
    positionTableNew(4) = heightTableNew;
    % positionTable = get(handles.t,'Position'); % [left, bottom, width, height]
    positionPanel = abs( get(handles.uipanel1, 'Position'));
    positionFigure = abs( get(handles.figure1, 'Position'));
    positionOuterFigure = abs( get(handles.figure1,'OuterPosition') );
    OffsetPanelTableHeight = positionPanel(4) - positionTable(4);
    OffsetFigureTableHeight = positionFigure(4) - positionTable(4);
    OffsetPanelTableWidth = positionPanel(3) - positionTable(3);
    OffsetFigureTableWidth = positionFigure(3) - positionTable(3);
    heigthPanelNew = positionTableNew(4) + OffsetPanelTableHeight;
    heigthFigureNew = positionTableNew(4) + OffsetFigureTableHeight;
    widthPanelNew = positionTableNew(3) + OffsetPanelTableWidth;
    widthFigureNew = positionTableNew(3) + OffsetFigureTableWidth;
    positionPanelNew = positionPanel;
    positionFigureNew = positionFigure;
    positionPanelNew(4) = round(heigthPanelNew);
    positionFigureNew(4) = round(heigthFigureNew);
    positionPanelNew(3) = round(widthPanelNew);
    positionFigureNew(3) = round(widthFigureNew);
    deltaHeight = positionFigureNew(4) - positionFigure(4);
    deltaOuterPos = positionOuterFigure - positionFigure;
    % Correct the bottom of the figure to avoid growing of figure to the top
    positionFigureNew(2) = round(positionFigureNew(2) - deltaHeight);
    positionOuterFigureNew = deltaOuterPos + positionFigureNew;
    if any([ positionPanelNew positionFigureNew positionOuterFigureNew positionTableNew] < 0)
        save('workspace@import_dynamic_params');
        figResize(handles.figure1,eventdata,handles);
        %     error('Position vector for graphic objects must be > 0');
    else
        break;
    end
end
set(handles.figure1,'Position',positionFigureNew,...
    'OuterPosition',positionOuterFigureNew);
set(handles.uipanel1,'Position',positionPanelNew);
set(handles.t,'RowName',rownames,'Data',dataNew,...
    'Position',positionTableNew,'ColumnWidth',columnwidth);
figResize(handles.figure1,eventdata,handles);