Description of add
Home > mtids > subfunctions > matgraph > @graph > add.m
add
PURPOSE
add --- add edge(s) to the graph
SYNOPSIS
function add(g,i,j,dir)
DESCRIPTION
 add --- add edge(s) to the graph
 add(g,i,j) --- adds the edge ij
 add(g,i,j,dir) -- treats the graph as directed
 add(g,elist) --- adds edges specified in elist to the graph
                  elist is an n-by-2 array of edges
 If an end point is larger than the number of vertices, the graph is
 extended. End points must be positive integers. Loops are ignored.
CROSS-REFERENCE INFORMATION
This function calls:
full full(g) --- convert internal storage for g to full
isfull isfull(g) --- check if g's adjacency matrix is full
nv nv(g) --- number of vertices in g
resize resize(g,n) --- change the number of vertices in g to n
size size(g) --- returns [nv,ne] for the graph
sparse sparse(g) --- convert internal storage for g to sparse
nv nv(p) --- number of vertices (elements) of a partition
size size(p) --- returns [nv,np]: number of vertices, parts.
set_large set_large(n) --- set the cut off size for large graphs.
This function is called by:
mtids MTIDS Version 1.2
bfstree bfstree(t,g,v) --- create a breadth-first spanning tree of g
bridges bridges(g,algo) --- find all cut edges in g
cartesian cartesian(g,h1,h2) --- overwrite g with the product of h1 and h2
cayley cayley(g,perms) -- create a Cayley graph (undirected)
circulant circulant(g,n,k) --- overwrite g with an n,k circulant graph
contract contract(g,u,v) --- contract v into u
cube cube(g,k) --- create a k-cube (default k = 3)
cycle cycle(g,n) --- create a cycle graph on n vertices
dfstree dfstree(t,g,v) --- create a depth-first spanning tree of g
dodecahedron dodecahedron(g) --- overwrite g with the dodecahedron graph
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
graph graph: constructor for the graph class
grid grid(g,a,b) --- create an a-by-b grid graph
hamiltonian_cycle hamiltonian_cycle(g) --- find a Hamiltonian cycle in g (if one exists)
icosahedron icosahedron(g) --- overwrite g with the icosahedron graph
interval_graph interval_graph(g,ilist) --- create an interval graph
line_graph line_graph(g,h) --- set g to be the line graph of h
load load(g,filename) --- read a saved graph on disk
mobius mobius(g,nverts) --- create a Mobius ladder graph
octahedron octahedron(g) --- overwrite g with the octahedron graph, K(2,2,2)
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
paley paley(g,n) --- create a Paley graph with n vertices
path path(g,n) --- make g a path on n vertices
petersen petersen(g) --- overwrite g with the Petersen graph
prufer prufer --- convert a tree to/from its Prufer code
random_planar random_planar(g,n) --- create a random planar triangulation
random_regular random_regular(g,n,k) --- create a random regular graph
random_tree random_tree(t,n) --- overwrite t with a random tree on n vertices
selective selective(g,n,n0,d) --- selective attachment random graph
sgf sgf --- simple graph format: a 2-column matrix representation
shiftgraph shiftgraph(g,k,t) -- create a shiftgraph g based on t-tuples of k symbols
sl2graph sl2graph(g,p) -- create an SL(2,p) graph
wheel wheel(g,n) --- overwrite g with a wheel graph on n vertices
edraw
hamiltonian % Finding and displaying Hamiltonian cycles in Matgraph
isomorphism % Checking graph isormorphism in Matgraph
SOURCE CODE
function add(g,i,j,dir)
% add --- add edge(s) to the graph
% add(g,i,j) --- adds the edge ij
% add(g,i,j,dir) -- treats the graph as directed
% add(g,elist) --- adds edges specified in elist to the graph
%                  elist is an n-by-2 array of edges
% If an end point is larger than the number of vertices, the graph is
% extended. End points must be positive integers. Loops are ignored.
global GRAPH_MAGIC
n = nv(g);
if nargin < 4
    dir = 0;
end
if (nargin == 3 || nargin == 4)
    if (i==j) || (i<1) || (j<1)
        return
    end
    maxij = max(i,j);
    if maxij > n
        resize(g,maxij)
    end
    if dir == 0;
        GRAPH_MAGIC.graphs{g.idx}.array(i,j) = 1;
        GRAPH_MAGIC.graphs{g.idx}.array(j,i) = 1;
        return
    end
    if dir == 1
        GRAPH_MAGIC.graphs{g.idx}.array(i,j) = 1;
        return
    end
end
if nargin == 2
    [nr,nc] = size(i);
    % check shape
    if (nc ~= 2)
        error('in add(elist), elist should have exactly two columns');
    end
    maxv = max(max(i));
    if maxv > n
        if maxv > set_large
            sparse(g)
        end
        resize(g,maxv)
    end
    n = nv(g);
    was_full = isfull(g);
    data = [i; n,n]; % note phony last row
    m = size(data,1);
    data = [data, ones(m,1)];
    A = spconvert(double(data));
    for k=1:n
        A(k,k)=0;
    end
    A = (A+A')>0;
    A = logical(A);
    if (was_full)
        A = full(A);
    end
    GRAPH_MAGIC.graphs{g.idx}.array = GRAPH_MAGIC.graphs{g.idx}.array | A;
    return
end