Description of dfstree
Home > mtids > subfunctions > matgraph > @graph > dfstree.m
dfstree
PURPOSE
dfstree(t,g,v) --- create a depth-first spanning tree of g
SYNOPSIS
function visited = dfstree(t,g,v)
DESCRIPTION
 dfstree(t,g,v) --- create a depth-first spanning tree of g
 The tree is rooted a the vertex v (or vertex 1 if missing). If g is not
 connected, we generate a tree only for the component containing v;
 vertices in the other components are isolated vertices in t.
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
clear_edges clear_edges(g) --- delete all edges of g
copy copy(g,h) --- overwrite g with a copy of h
copy_labels copy_labels(g,h) --- copy labels from h to g
embed embed --- create an embedding for a graph
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
hasxy hasxy(g) --- determine if an embedding has been created for g
is_labeled is_labeled(g) --- determine if there are labels on vertices.
neighbors neighbors(g,v) --- neighbors of v as a list.
nv nv(g) --- number of vertices in g
q_init q_init(n) --- initialize private queue with capacity n
nv nv(p) --- number of vertices (elements) of a partition
This function is called by:
compute_SCC COMPUTE_SCC Computes strong connected components of a digraph
compute_WCC COMPUTE_WCC Computes weak connected components of a digraph
spanning_tree % Finding spanning trees
SUBFUNCTIONS
function visited = tree_build(t,g,v,visited)
SOURCE CODE
function visited = dfstree(t,g,v)
% dfstree(t,g,v) --- create a depth-first spanning tree of g
% The tree is rooted a the vertex v (or vertex 1 if missing). If g is not
% connected, we generate a tree only for the component containing v;
% vertices in the other components are isolated vertices in t.
if nargin==2
    v = 1;
end
n = nv(g);
if (v<0) || (v>n)
    error('Seed vertex out of range')
end
copy(t,g);
clear_edges(t);
q_init(2*n+1);
visited = zeros(n,1);
visited = tree_build(t,g,v,visited);
if is_labeled(g)
    copy_labels(t,g);
end
if hasxy(g)
    embed(t,getxy(g))
end
end
function visited = tree_build(t,g,v,visited)
% recursively build DFS tree
visited(v) = 1;
nlist = neighbors(g,v);
for w = nlist
    if (~visited(w))
        add(t,v,w);
        visited = tree_build(t,g,w,visited);
    end
end
end