Description of free
Home > mtids > subfunctions > matgraph > @graph > free.m
free
PURPOSE
free(g) --- free the graph from the system
SYNOPSIS
function free(g)
DESCRIPTION
 free(g) --- free the graph from the system
CROSS-REFERENCE INFORMATION
This function calls:
graph_system_exists graph_system_exists checks to see if the GRAPH_MAGIC global structure has
This function is called by:
mtids MTIDS Version 1.2
bridges bridges(g,algo) --- find all cut edges in g
cube cube(g,k) --- create a k-cube (default k = 3)
edge_color edge_color(g,algo) --- find a proper edge coloring of the graph g
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
intersect intersect(g,h1,h2) --- g is set to the intersection of h1 and h2.
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
chromatic_poly chromatic_poly(g) --- find the chromatic polynomial of g
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
iso [yn,p] = iso(g,h) --- is g isomorphic to h?
omega [w,S] = omega(g) --- clique number
prufer prufer --- convert a tree to/from its Prufer code
random_regular random_regular(g,n,k) --- create a random regular graph
union union(g,h1,h2) --- set g equal to the union of h1 and h2.
cayley_graph % Creating a Cayley graph
coloring % Coloring graphs in Matgraph
domination % Domination in graphs
edraw
eulerian % Eulerian tours
hamiltonian % Finding and displaying Hamiltonian cycles in Matgraph
isomorphism % Checking graph isormorphism in Matgraph
matching % Matchings in bipartite graphs
ramsey % Lower bound for the Ramsey number R(4)
spanning_tree % Finding spanning trees
splitter % Splitting the vertex set of a graph
SOURCE CODE
function free(g)
% free(g) --- free the graph from the system
if ~graph_system_exists
    error('Graph system has not been initialized')
end
global GRAPH_MAGIC
i = g.idx;
GRAPH_MAGIC.in_use(i) = 0;
GRAPH_MAGIC.graphs{i} = [];