Description of has
Home > mtids > subfunctions > matgraph > @graph > has.m
has
PURPOSE
has --- check if the graph has a particular vertex or edge
SYNOPSIS
function yn = has(g,u,v,dir)
DESCRIPTION
 has --- check if the graph has a particular vertex or edge
 has(g,u) --- check if g contains the vertex u
 has(g,u,v) --- check if g contains the edge uv
 has(g,u,v,dir) -- treats 'g' as directed
CROSS-REFERENCE INFORMATION
This function calls:
nv nv(g) --- number of vertices in g
nv nv(p) --- number of vertices (elements) of a partition
This function is called by:
mtids MTIDS Version 1.2
bridges bridges(g,algo) --- find all cut edges in g
cartesian cartesian(g,h1,h2) --- overwrite g with the product of h1 and h2
hamiltonian_cycle hamiltonian_cycle(g) --- find a Hamiltonian cycle in g (if one exists)
draw draw(g) --- draw g in a figure window
springxy springxy(g) --- find a spring embedding of g
SOURCE CODE
function yn = has(g,u,v,dir)
% has --- check if the graph has a particular vertex or edge
% has(g,u) --- check if g contains the vertex u
% has(g,u,v) --- check if g contains the edge uv
% has(g,u,v,dir) -- treats 'g' as directed
global GRAPH_MAGIC;
if nargin < 4
    dir = 0;
end
n = nv(g);
if (nargin==2)
    yn = (u>0) & (u<=n);
elseif nargin == 3
    if (u<0) || (u>n) || (v<0) || (v>n) || (u==v)
        yn = 0;
    else
        yn = GRAPH_MAGIC.graphs{g.idx}.array(u,v);
    end
elseif (nargin == 4 && dir == 1) %it's useless, the function works well for directed graphs too
    if (u<0) || (u>n) || (v<0) || (v>n) || (u==v)
        yn = 0;
    else
        yn = GRAPH_MAGIC.graphs{g.idx}.array(u,v);
    end
end