Description of ndraw
Home > mtids > subfunctions > matgraph > @graph > ndraw.m
ndraw
PURPOSE
ndraw(g) --- draw g in a figure window with numbered vertices
SYNOPSIS
function ndraw(g,dir,line_style,nodeFillColor,nodeEdgeColor)
DESCRIPTION
 ndraw(g) --- draw g in a figure window with numbered vertices
 ndraw(g,dir) --- treat g as directed
 ndraw(g,dir,line_style) --- lines have given line_style
 see also draw, ldraw, and cdraw
CROSS-REFERENCE INFORMATION
This function calls:
draw draw(g) --- draw g in a figure window
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
nv nv(g) --- number of vertices in g
draw draw(g) --- draw g in a figure window
nv nv(p) --- number of vertices (elements) of a partition
This function is called by:
mtids MTIDS Version 1.2
ldraw ldraw(g,dir) -- draw a graph with vertices marked with their labels
eulerian % Eulerian tours
isomorphism % Checking graph isormorphism in Matgraph
SOURCE CODE
function ndraw(g,dir,line_style,nodeFillColor,nodeEdgeColor)
% ndraw(g) --- draw g in a figure window with numbered vertices
% ndraw(g,dir) --- treat g as directed
% ndraw(g,dir,line_style) --- lines have given line_style
% see also draw, ldraw, and cdraw
if nargin < 2
    dir = 0;
    draw(g,dir);
end
if nargin < 3
   draw(g,dir,'-');
else
    draw(g,dir,line_style,nodeFillColor,nodeEdgeColor);
end
xy = getxy(g);
n = nv(g);
for v=1:n
    x = xy(v,1);
    y = xy(v,2);
    text(x-.05,y,int2str(v));
end