Description of ne
Home > mtids > subfunctions > matgraph > @graph > ne.m
ne
PURPOSE
ne(g) --- number of edges in g
SYNOPSIS
function m = ne(g,dir,h)
DESCRIPTION
 ne(g) --- number of edges in g
 ne(g,dir) -- number of edges in g, if g is a directed graph and dir == 1
 ne(g,dir,h) --- check for inequality
CROSS-REFERENCE INFORMATION
This function calls:
size size(g) --- returns [nv,ne] for the graph
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
mtids MTIDS Version 1.2
adj_to_elist ADJ_TO_ELIST Reshapes an (N x N) adjacency matrix into a (M x 2) edge list
bipartition part = bipartition(g) --- find bipartition of a bipartite graph
bridges bridges(g,algo) --- find all cut edges in g
cdraw cdraw(g,dir,coloring) -- draw g with a given vertex coloring
display display(g) --- display basic information about a graph object
dot dot(g,filename) --- save graph for use by graphviz.
draw draw(g) --- draw g in a figure window
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
graffle graffle(g, filename, width, rad) --- write graph in OmniGraffle format
chromatic_poly chromatic_poly(g) --- find the chromatic polynomial of g
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
prufer prufer --- convert a tree to/from its Prufer code
random_regular random_regular(g,n,k) --- create a random regular graph
save save(g,filename) --- save a graph to disk
sgf sgf --- simple graph format: a 2-column matrix representation
size size(g) --- returns [nv,ne] for the graph
SOURCE CODE
function m = ne(g,dir,h)
% ne(g) --- number of edges in g
% ne(g,dir) -- number of edges in g, if g is a directed graph and dir == 1
% ne(g,dir,h) --- check for inequality
global GRAPH_MAGIC
if nargin < 2
    dir = 0;
end
if (nargin == 3 && dir == 0)
    if any(size(g) ~= size(h))
        m = 1;
        return
    end
    D = GRAPH_MAGIC.graphs{g.idx}.array - GRAPH_MAGIC.graphs{h.idx}.array;
    m = nnz(D)>0;
    return
end
if (nargin == 2 && dir ~= 0)
    m = nnz(GRAPH_MAGIC.graphs{g.idx}.array);
    return
end
m = nnz(GRAPH_MAGIC.graphs{g.idx}.array)/2;