Description of random
Home > mtids > subfunctions > matgraph > @graph > random.m
random
PURPOSE
random --- overwrite g with a random graph
SYNOPSIS
function random(g,arg1,arg2)
DESCRIPTION
 random --- overwrite g with a random graph
 random(g,n,p) --- overwrite g with an Erdos-Renyi G(n,p) graph
 random(g,p) --- overwrite g with an Erdos-Reniy G(n,p) graph where n is
                 the number of vertices already in g.
 random(g) --- equivalent to random(g,1/2)
CROSS-REFERENCE INFORMATION
This function calls:
fast_set_matrix fast_set_matrix(g,A) --- overwrite the adjacency matrix of g with A
nv nv(g) --- number of vertices in g
random random --- overwrite g with a random graph
sparse sparse(g) --- convert internal storage for g to sparse
nv nv(p) --- number of vertices (elements) of a partition
This function is called by:
mtids MTIDS Version 1.2
random random --- overwrite g with a random graph
isomorphism % Checking graph isormorphism in Matgraph
perm % Permutations in Matgraph
SOURCE CODE
function random(g,arg1,arg2)
% random --- overwrite g with a random graph
% random(g,n,p) --- overwrite g with an Erdos-Renyi G(n,p) graph
% random(g,p) --- overwrite g with an Erdos-Reniy G(n,p) graph where n is
%                 the number of vertices already in g.
% random(g) --- equivalent to random(g,1/2)
% case: random(g,n,p)
if nargin==3
    n = arg1;
    p = arg2;
    A = triu(rand(n,n)<=p);
    A = A+A';
    for k=1:n
        A(k,k)=0;
    end
    fast_set_matrix(g,A);
    return
end
% case: random(g,p)
if nargin==2
    n = nv(g);
    p = arg1;
    random(g,n,p);
    return
end
% last case: random(g)
%random(g,0.5);
n = nv(g);
A = rand(n);
A = A < 0.5; % or even larger, is doesn't matter
for i=1:length(A)
    A(i,i) = 0;
end
fast_set_matrix(g,sparse(A));