Description of delete
Home > mtids > subfunctions > matgraph > @graph > delete.m
delete
PURPOSE
delete --- delete vertices or edges from a graph
SYNOPSIS
function delete(g,i,j,dir)
DESCRIPTION
 delete --- delete vertices or edges from a graph
 delete(g,v) --- delete vertex v
 delete(g,vlist) --- delete vertices in column vector v
 delete(g,i,j) --- delete edge ij
 delete(g,i,j,dir) -- delete edge while treating g as directed graph
 delete(g,elist) --- delete edges in m-by-2 array elist
CROSS-REFERENCE INFORMATION
This function calls:
delete delete --- delete vertices or edges from a graph
hasxy hasxy(g) --- determine if an embedding has been created for g
is_labeled is_labeled(g) --- determine if there are labels on vertices.
nv nv(g) --- number of vertices in g
size size(g) --- returns [nv,ne] for the graph
nv nv(p) --- number of vertices (elements) of a partition
size size(p) --- returns [nv,np]: number of vertices, parts.
This function is called by:
mtids MTIDS Version 1.2
about_mtids ABOUT_MTIDS M-file for about_mtids.fig
editSimParams EDITSIMPARAMS gui for asking basic Simulink simulation parameters
edit_node EDIT_NODE gui to edit settings of a specific node in a MTIDS graph
edit_paramValues EDIT_PARAMVALUES gui to edit numerical parameter values of a template
import_dynamic_params IMPORT_DYNAMIC_PARAMS gui for importing tempates to MTIDS
inputParamsAdaptation INPUTPARAMSADAPTATION gui to choose how input parameters should corrected
manageParamSets MANAGEPARAMSETS gui for managing templates and its numerical parameter sets
pp2 PP2 gui to set the plot specifications for each signal to plot
setnodecolor SETNODECOLOR gui to set the appearance of the nodes in MTIDS
bridges bridges(g,algo) --- find all cut edges in g
contract contract(g,u,v) --- contract v into u
delete delete --- delete vertices or edges from a graph
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
chromatic_poly chromatic_poly(g) --- find the chromatic polynomial of g
euler_trail euler_trail(g) --- find an euler trail in g (if one exists)
prufer prufer --- convert a tree to/from its Prufer code
trim trim(g,d) --- iteratively remove vertices of degree at most d
eulerian % Eulerian tours
testingValueSet TESTINGVALUESET checking numerical parameters of template
SOURCE CODE
function delete(g,i,j,dir)
% delete --- delete vertices or edges from a graph
% delete(g,v) --- delete vertex v
% delete(g,vlist) --- delete vertices in column vector v
% delete(g,i,j) --- delete edge ij
% delete(g,i,j,dir) -- delete edge while treating g as directed graph
% delete(g,elist) --- delete edges in m-by-2 array elist
global GRAPH_MAGIC
n = nv(g);
% This a true argument "dir" is passed, the graph will be treated as
% directed and only the entry (i,j) in the adjacency matrix will be erased
if (nargin > 3 && dir == 1)
   if (i<1) || (i>n) || (j<1) || (j>n)
       return
   end
   GRAPH_MAGIC.graphs{g.idx}.array(i,j) = 0;
   return
end
if nargin==3   % simple delete an edge
   if (i<1) || (i>n) || (j<1) || (j>n)
       return
   end
   GRAPH_MAGIC.graphs{g.idx}.array(i,j) = 0;
   GRAPH_MAGIC.graphs{g.idx}.array(j,i) = 0;
   return
end
% from here on, we're in the single argument case
[nr,nc] = size(i);
% delete a set of vertices (or a single vertex)
if  (nc==1)
    kill_list = i(find((i>0) & (i<=n)));
    keep_list = setdiff(1:n,kill_list);
    if hasxy(g)
        GRAPH_MAGIC.graphs{g.idx}.xy = ...
            GRAPH_MAGIC.graphs{g.idx}.xy(keep_list,:);
    end
    if is_labeled(g)
        GRAPH_MAGIC.graphs{g.idx}.labels = ...
            GRAPH_MAGIC.graphs{g.idx}.labels(keep_list);
    end
    GRAPH_MAGIC.graphs{g.idx}.array = ...
        GRAPH_MAGIC.graphs{g.idx}.array(keep_list,keep_list);
    return
end
if (nr==1) && (nc ~=2)
    error('for delete(g,vlist), vlist must be a single COLUMN vector');
end
% finally, we're in the delete a list of edges case
if (nc ~= 2)
    error('delete(elist) requires elist to have exactly two columns')
end
for k=1:nr
    delete(g,i(k,1),i(k,2));
end