Description of ldraw
Home > mtids > subfunctions > matgraph > @graph > ldraw.m
ldraw
PURPOSE
ldraw(g,dir) -- draw a graph with vertices marked with their labels
SYNOPSIS
function ldraw(g,dir,line_style,nodeFillColor,nodeEdgeColor)
DESCRIPTION
 ldraw(g,dir) -- draw a graph with vertices marked with their labels
                 and treat it as directed, if dir == 1
 ldraw(g,dir,line_style) --- give additional line_style
 If the graph is unlabled, we use the vertex numbers instead.
 See also draw, cdraw, and ndraw.
CROSS-REFERENCE INFORMATION
This function calls:
draw draw(g) --- draw g in a figure window
draw_labels draw_labels(g) --- add labels to a drawing of g
is_labeled is_labeled(g) --- determine if there are labels on vertices.
ndraw ndraw(g) --- draw g in a figure window with numbered vertices
draw draw(g) --- draw g in a figure window
This function is called by:
mtids MTIDS Version 1.2
cayley_graph % Creating a Cayley graph
SOURCE CODE
function ldraw(g,dir,line_style,nodeFillColor,nodeEdgeColor)
% ldraw(g,dir) -- draw a graph with vertices marked with their labels
%                 and treat it as directed, if dir == 1
% ldraw(g,dir,line_style) --- give additional line_style
% If the graph is unlabled, we use the vertex numbers instead.
% See also draw, cdraw, and ndraw.
if ~is_labeled(g)
    if nargin ==1
        dir = 0;
        ndraw(g,dir);
        return
    elseif nargin == 2
        ndraw(g,dir);
        return
    else
        ndraw(g,dir,line_style,nodeFillColor,nodeEdgeColor)
        return
    end
end
if nargin == 1
    dir = 0;
    draw(g,dir);
elseif nargin == 2
    draw(g,dir);
else
    draw(g,dir,line_style,nodeFillColor,nodeEdgeColor);
end
draw_labels(g);