Description of random_tree
Home > mtids > subfunctions > matgraph > @graph > random_tree.m
random_tree
PURPOSE
random_tree(t,n) --- overwrite t with a random tree on n vertices
SYNOPSIS
function random_tree(t,n)
DESCRIPTION
 random_tree(t,n) --- overwrite t with a random tree on n vertices
CROSS-REFERENCE INFORMATION
This function calls:
add add --- add edge(s) to the graph
clear_edges clear_edges(g) --- delete all edges of g
renumber renumber the vertices of a graph
resize resize(g,n) --- change the number of vertices in g to n
This function is called by:
isomorphism % Checking graph isormorphism in Matgraph
matching % Matchings in bipartite graphs
splitter % Splitting the vertex set of a graph
SOURCE CODE
function random_tree(t,n)
% random_tree(t,n) --- overwrite t with a random tree on n vertices
resize(t,n);
clear_edges(t);
for v=2:n
    u = floor(rand(1)*(v-1))+1;
    add(t,u,v);
end
p = randperm(n);
renumber(t,p);