Description of q_size
Home > mtids > subfunctions > matgraph > @graph > private > q_size.m
q_size
PURPOSE
determine the number of elements held in the queue
SYNOPSIS
function n = q_size
DESCRIPTION
 determine the number of elements held in the queue
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
bfstree bfstree(t,g,v) --- create a breadth-first spanning tree of g
find_path find_path(g,u,v) --- find a shortest path from u to v
q_get q_get --- get the values held in the queue
SOURCE CODE
function n = q_size
% determine the number of elements held in the queue
global GRAPH_MAGIC
n = GRAPH_MAGIC.Q.last - GRAPH_MAGIC.Q.first + 1;