Description of inv
Home > mtids > subfunctions > matgraph > @permutation > inv.m
inv
PURPOSE
inv(p) returns the inverse permutation of p
SYNOPSIS
function q = inv(p)
DESCRIPTION
 inv(p) returns the inverse permutation of p
CROSS-REFERENCE INFORMATION
This function calls:
array array(p) --- return a single array showing the part numbers of elements.
array array(p) --- return p as an array
permutation constructor for the permutation class
This function is called by:
iso [yn,p] = iso(g,h,options) --- is g isomorphic to h?
iso [yn,p] = iso(g,h) --- is g isomorphic to h?
renumber renumber the vertices of a graph
mpower p^t is p multiplied by itself t times. May have t <= 0.
perm % Permutations in Matgraph
SOURCE CODE
function q = inv(p)
% inv(p) returns the inverse permutation of p
a = array(p);
[y,b] = sort(a);
q = permutation(b);