Description of mtids
Home > mtids > mtids.m
mtids
PURPOSE
MTIDS Version 1.2
SYNOPSIS
function varargout = mtids(varargin)
DESCRIPTION
MTIDS Version 1.2
      (C) 2011 The MTIDS Project (http://code.google.com/p/mtids)
      Matlab Toolbox for Interconnected Dynamical Systems
      Test Rig for Large-Scale Interconnected Systems.
      MTIDS uses and redistributes Matgraph (C) 2005 Ed Scheinermann (http://www.ams.jhu.edu/~ers/matgraph/)
CROSS-REFERENCE INFORMATION
This function calls:
computeInputSizes COMPUTEINPUTSIZES Computes signal sizes of nodes inputs
compute_SCC COMPUTE_SCC Computes strong connected components of a digraph
compute_WCC COMPUTE_WCC Computes weak connected components of a digraph
about_mtids ABOUT_MTIDS M-file for about_mtids.fig
editSimParams EDITSIMPARAMS gui for asking basic Simulink simulation parameters
edit_node EDIT_NODE gui to edit settings of a specific node in a MTIDS graph
export_as_matrix EXPORT_AS_MATRIX gui to export a graph in mtids as a matrix
import_dynamic_params IMPORT_DYNAMIC_PARAMS gui for importing tempates to MTIDS
manageParamSets MANAGEPARAMSETS gui for managing templates and its numerical parameter sets
setnodecolor SETNODECOLOR gui to set the appearance of the nodes in MTIDS
getDegree GETDEGREE Computes in- and outdegree of a node in a digraph
initPlotParams INITPLOTPARAMS initially set the parameters needed for plots
any_matrix_to_elist ANY_MATRIX_TO_ELIST Reshapes an adjacency matrix into an edge list
exportLayer exportLayer.m
exportLayer2 exportLayer.m
exportSimulink exportSimulink.m
exportSimulink2 EXPORTSIMULINK2 creates Simulink system out of MTIDS graph
importSimulink importSimulink.m :
add add --- add edge(s) to the graph
clear_edges clear_edges(g) --- delete all edges of g
complete complete: build complete and complete multipartite graphs
delete delete --- delete vertices or edges from a graph
draw draw(g) --- draw g in a figure window
edges edges(g) --- list the edges in g as a 2-column matrix
eig eig(g) -- compute the eigenvalues of this graph
embed embed --- create an embedding for a graph
free free(g) --- free the graph from the system
get_label get_label(g) or get_label(g,v) --- get vertex label(s)
getxy getxy(g) --- give g's embedding (or [] if g doesn't have one)
graph graph: constructor for the graph class
has has --- check if the graph has a particular vertex or edge
label Assign labels to vertices of g
laplacian laplacian(g) --- get the Laplacian matrix of g
ldraw ldraw(g,dir) -- draw a graph with vertices marked with their labels
load load(g,filename) --- read a saved graph on disk
matrix matrix(g) --- return (a copy of) the adjacency matrix of g
matrixOfGraph matrix(g) --- return (a copy of) the adjacency matrix of g
ndraw ndraw(g) --- draw g in a figure window with numbered vertices
ne ne(g) --- number of edges in g
nv nv(g) --- number of vertices in g
draw draw(g) --- draw g in a figure window
path path(g,n) --- make g a path on n vertices
random random --- overwrite g with a random graph
resize resize(g,n) --- change the number of vertices in g to n
rmxy rmxy(g) --- erase g's embedding
save save(g,filename) --- save a graph to disk
size size(g) --- returns [nv,ne] for the graph
trim trim(g,d) --- iteratively remove vertices of degree at most d
check check(p) --- check that the datastructure holding p is a valid partition
ne ne(p,q) --- p ~= q checks if p and q are different
nv nv(p) --- number of vertices (elements) of a partition
size size(p) --- returns [nv,np]: number of vertices, parts.
ne test if p ~= q
graph_destroy destroy the GRAPH_MAGIC system
graph_init graph_init(capacity) --- used to initialize the GRAPH_MAGIC data
readImportedTemplates READIMPORTEDTEMPLATES reads Simulink templates out of folder
performSimulation PERFORMSIMULATION Simulates the MTIDS system in Simulink
systemConsistencyTest SYSTEMCONSISTENCYTEST compares input signal with input depending parameters
This function is called by:
SUBFUNCTIONS
function mtids_OpeningFcn(hObject, eventdata, handles, varargin)
function varargout = mtids_OutputFcn(hObject, eventdata, handles)
function newnodelabel_CreateFcn(hObject, eventdata, handles)
function newnode_Callback(hObject, eventdata, handles)
function figure1_CloseRequestFcn(hObject, eventdata, handles)
function addconnection_Callback(hObject, eventdata, handles)
function fromnode_CreateFcn(hObject, eventdata, handles)
function tonode_CreateFcn(hObject, eventdata, handles)
function randomconnection_Callback(hObject, eventdata, handles)
function removeconnection_Callback(hObject, eventdata, handles)
function remnode_CreateFcn(hObject, eventdata, handles)
function removenode_Callback(hObject, eventdata, handles)
function trimgraph_Callback(hObject, eventdata, handles)
function clearconnections_Callback(hObject, eventdata, handles)
function completegraph_Callback(hObject, eventdata, handles)
function randomgraph_Callback(hObject, eventdata, handles)
function listbox1_CreateFcn(hObject, eventdata, handles)
function Newgraph_Callback(hObject, eventdata, handles)
function loadgraph_Callback(hObject, eventdata, handles)
function savegraphas_Callback(hObject, eventdata, handles)
function aboutmtids_Callback(hObject, eventdata, handles)
function labelview_Callback(hObject, eventdata, handles)
function colorview_Callback(hObject, eventdata, handles)
function numberview_Callback(hObject, eventdata, handles)
function blankview_Callback(hObject, eventdata, handles)
function export_as_layer_2_Callback(hObject, eventdata, handles)
function refresh_graph(reset, eventdata, handles,hObject)
function basic_stats(eventdata, handles)
function dynamic_label_CreateFcn(hObject, eventdata, handles)
function import_from_simulink_Callback(hObject, eventdata, handles)
function export_to_simulink_Callback(hObject, eventdata, handles)
function add_multiple_nodes_Callback(hObject, eventdata, handles)
function exit_to_matlab_Callback(hObject, eventdata, handles)
function number_of_nodes_CreateFcn(hObject, eventdata, handles)
function label_button_Callback(hObject, eventdata, handles)
function number_button_Callback(hObject, eventdata, handles)
function export_to_workplace_Callback(hObject, eventdata, handles)
function import_from_workplace_Callback(hObject, eventdata, handles)
function add_mdl_template_Callback(hObject, eventdata, handles)
function selector_dynamic_CreateFcn(hObject, eventdata, handles)
function selector_dynamic_Callback(hObject, eventdata, handles)
function selector_valueSet_CreateFcn(hObject, eventdata, handles)
function refresh_dynamics(eventdata, handles)
function refresh_valueSet(handles)
function circular_graph_Callback(hObject, eventdata, handles)
function figure1_WindowButtonDownFcn(hObject, eventdata, handles)
function figure1_WindowButtonUpFcn(hObject, eventdata, handles)
function figure1_WindowButtonMotionFcn(hObject, eventdata, handles)
function export_as_layer_Callback(hObject, eventdata, handles)
function update_graph_button_Callback(hObject, eventdata, handles)
function export_to_simulink2_Callback(hObject, eventdata, handles)
function uipanel9_SelectionChangeFcn(hObject, eventdata, handles)
function run_simulation_Callback(hObject, eventdata, handles)
function plotAllOutput_Callback(hObject, eventdata, handles)
function run_simulation_plots_Callback(hObject, eventdata, handles)
function pushbutton17_Callback(hObject, eventdata, handles)
function showSimMod_Callback(hObject, eventdata, handles)
function load_settings(filename,handles)
function save_settings(filename,handles)
function loadGraphAtOpening(hObject, eventdata, handles)
function set_node_color_Callback(hObject, eventdata, handles)
function create_dynamic_Template_Callback(hObject, eventdata, handles)
function template_import_wizard_Callback(hObject, eventdata, handles)
function saveGraph(hObject, eventdata, handles, pathname, filename)
function menu_manageParamSets_Callback(hObject, eventdata, handles)
function get_simParams_Callback(hObject, eventdata, handles)
function radiobutton7_Callback(hObject, eventdata, handles)
function tonode_Callback(hObject, eventdata, handles)
function fromnode_Callback(hObject, eventdata, handles)
function Untitled_10_Callback(hObject, eventdata, handles)
function file_Callback(hObject, eventdata, handles)
function Untitled_9_Callback(hObject, eventdata, handles)
function Untitled_11_Callback(hObject, eventdata, handles)
function generatesimulinkmdl_Callback(hObject, eventdata, handles)
function Untitled_12_Callback(hObject, eventdata, handles)
function figure1_ResizeFcn(hObject, eventdata, handles)
function listbox1_Callback(hObject, eventdata, handles)
function about_Callback(hObject, eventdata, handles)
function adddynamics_Callback(hObject, eventdata, handles)
function dynamicsimporter_Callback(hObject, eventdata, handles)
function checkbox2_Callback(hObject, eventdata, handles)
function figure1_KeyPressFcn(hObject, eventdata, handles)
function Savegraph_Callback(hObject, eventdata, handles)
function Untitled_17_Callback(hObject, eventdata, handles)
function viewmenu_Callback(hObject, eventdata, handles)
function editnode_Callback(hObject, eventdata, handles)
function Untitled_13_Callback(hObject, eventdata, handles)
function Untitled_14_Callback(hObject, eventdata, handles)
function click_add_node_long_Callback(hObject, eventdata, handles)
function remnode_Callback(hObject, eventdata, handles)
function dynamic_label_Callback(hObject, eventdata, handles)
function number_of_nodes_Callback(hObject, eventdata, handles)
function selector_valueSet_Callback(hObject, eventdata, handles)
SOURCE CODE
function varargout = mtids(varargin)
%MTIDS Version 1.2
%      (C) 2011 The MTIDS Project (http://code.google.com/p/mtids)
%      Matlab Toolbox for Interconnected Dynamical Systems
%      Test Rig for Large-Scale Interconnected Systems.
%
%      MTIDS uses and redistributes Matgraph (C) 2005 Ed Scheinermann (http://www.ams.jhu.edu/~ers/matgraph/)
%      This program is free software; you can redistribute it and/or
%      modify it under the terms of the GNU General Public License
%      as published by the Free Software Foundation; either version 2
%      of the License, or (at your option) any later version.
%
%      This program is distributed in the hope that it will be useful,
%      but WITHOUT ANY WARRANTY; without even the implied warranty of
%      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%      GNU General Public License for more details.
%
%      You should have received a copy of the GNU General Public License
%      along with this program; if not, write to the Free Software
%      Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
%
%       A copy of the GNU GPL v2 Licence is available inside the LICENCE.txt
%       file.
%
% Last Modified by GUIDE v2.5 26-Sep-2012 15:38:36
% Authors: Francisco Llobet, Jose Rivera
% Editor: Ferdinand Trommsdorff (f.trommsdorff@gmail.com)
% Project: MTIDS (http://code.google.com/p/mtids/)
% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @mtids_OpeningFcn, ...
                   'gui_OutputFcn',  @mtids_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes just before mtids is made visible.
function mtids_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to mtids (see VARARGIN)
disp(' ');
disp('MTIDS 1.2');
disp('Test Rig for Large-Scale and Interconnected Dynamical Systems');
disp('<a href="http://code.google.com/p/mtids">http://code.google.com/p/mtids</a>');
disp(' ');
disp('This program is free software; you can redistribute it and/or');
disp('modify it under the terms of the GNU General Public License');
disp('as published by the Free Software Foundation; either version 2');
disp('of the License, or (at your option) any later version.');
disp('This program is distributed in the hope that it will be useful,');
disp('but WITHOUT ANY WARRANTY; without even the implied warranty of');
disp('MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the');
disp('GNU General Public License for more details.');
disp(' ');
disp('You should have received a copy of the GNU General Public License');
disp('along with this program; if not, write to the Free Software');
disp('Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.');
disp(' ');
disp(' ');
%--------------------------------------------------------------------------
%----------------INITIALISE PARAMETERS-------------------------------------
%--------------------------------------------------------------------------
initPath = mfilename('fullpath');
% extract path where mtids is localized
initPath = initPath(1:end-5);
cd(initPath);
addpath(strcat(pwd,'/subfunctions/matgraph'));                     % Folder with a copy of Matgraph
addpath(strcat(pwd,'/templates'));                          % Folder for Simulink templates
addpath(strcat(pwd,'/templates/import'));                   % Folder with importes templates
addpath(strcat(pwd,'/subfunctions'));                       % Folder with GUIs and functions
addpath(strcat(pwd,'/subfunctions/interface2Simulink'));    % Folder with various import/export functions
addpath(strcat(pwd,'/subfunctions/mtids_main'));
addpath(strcat(pwd,'/resources'));                          % Folder with resource files like manuals, graphics, etc.
addpath(strcat(pwd,'/subfunctions/figures'));
%initialize graph
graph_init;
%declare userdata as structures: data.*; with it global variables could be
%erased
flagLoadSet = 0;
try
    load_settings(['resources' filesep 'lastset'],handles);
    data = getappdata(handles.figure1,'appData');
    if ~isempty(data)
        choice = questdlg('Do you want to load the settings formerly used?', ...
            'Former settings?', ...
            'Yes','Yes, with last graph','No','No');
        switch choice
            case 'Yes';
                flagLoadSet = 1;
            case 'Yes, with last graph';
                loadGraphAtOpening(hObject, eventdata, handles);
                data = getappdata(handles.figure1,'appData');
                flagLoadSet = 2;
            case 'No';
                flagLoadSet = 0;
        end
    end
catch
    %
end
% Setting the parameters according to chosen old data
switch flagLoadSet
    case 1;
        data.templates = cell(0,1);
        data.printCell = cell(0,2);
        data.nodeColor = cell(0,2);
        g = graph; %% Creating a graph
        resize(g,0);
        data.g = g;
    case 2;
    otherwise;
        data.plotAllOutput = 1;
        data.flag_showSimMod = 1;
        data.template_list = cell(0,3);
        data.modus = 'undirected';
%         % template_list-data for debugging/testing-purpose
%         data.template_list{1,1} = 'LTI';
%         data.template_list{1,2} = [245 245 245]/255; % node face color for template
%         data.template_list{1,3} = [0 0 0]; % node edge color for template
%         paramValues(1).set = cell(1,3); % param values
%         data.template_list{1,4} = paramValues;
%         data.template_list{1,5} = 1; % is active (or not), logical
        data.templates = cell(0,1);
        data.printCell = cell(0,2);
        data.nodeColor = cell(0,2);
        g = graph; %% Creating a graph
        resize(g,0);
        data.g = g;
end
data.template_list = readImportedTemplates(data.template_list);
data.move_index = 0;
data.expSucc = 0;
data.botton_down = 0;
data.add_connection = 0;
data.start_index = 0;
data.graph_refresh = 1;
data.adaptInputParams = 'ones';
%container for plot information -
% 1.column: printVector -- containes the information about node number,
%internal states and which should be plotted
%2. column: plotParams -- the design information for the plot command, a
%struct with 6 elements per state
%       Example: a node has 3 int. states, 2 should be plotted, then
%       struct(1) and struct(2) exists, each with 6 elements
%--------------------------------------------------------------------------
%-------------------INITIALISE GUI-----------------------------------------
%--------------------------------------------------------------------------
if strcmp(data.modus, 'undirected')
    set(handles.button_undirected,'Value',1);
    set(handles.button_directed,'Value',0);
elseif strcmp(data.modus, 'directed')
    set(handles.button_undirected,'Value',0);
    set(handles.button_directed,'Value',1);
end
if data.plotAllOutput == 0
    set(handles.plotAllOutput,'Checked','off')
elseif data.plotAllOutput == 1
    set(handles.plotAllOutput,'Checked','on')
end
if data.flag_showSimMod == 0
    set(handles.showSimMod,'Checked','off')
elseif data.flag_showSimMod == 1
    set(handles.showSimMod,'Checked','on')
end
%grid on;
%zoom on;
set(handles.numberview,'Check','on');
set(handles.number_button,'Value', 1);
set(handles.newnodelabel,'String','Node');
set(handles.strong_connections,'String', ' ');
set(handles.text16,'String', 'Graph density:');
% store userdata, use tag 'appData'
setappdata(hObject,'appData',data);
refresh_dynamics(eventdata, handles);
% Choose default command line output for mtids
handles.output = hObject;
% Update handles structure
guidata(hObject, handles);
% refresh_valueSet(handles);
refresh_graph(0, eventdata, handles,hObject);
% UIWAIT makes mtids wait for user response (see UIRESUME)
% uiwait(handles.figure1);
% --- Outputs from this function are returned to the command line.
function varargout = mtids_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
varargout{1} = handles.output;
% --- Executes during object creation, after setting all properties.
function newnodelabel_CreateFcn(hObject, eventdata, handles)
% hObject    handle to newnodelabel (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on button press in newnode.
function newnode_Callback(hObject, eventdata, handles)
% hObject    handle to newnode (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
graph_refresh = data.graph_refresh;
templates = data.templates;
template_list = data.template_list;
printCell = data.printCell;
plotAllOutput = data.plotAllOutput;
rmxy(g);
new_vertex = nv(g) + 1;
resize(g, new_vertex);
labs = get_label(g);
lab_string =  get(handles.newnodelabel,'String');
% check if any of the existing names is equal as the new one
if any(strncmp(lab_string,labs,length(lab_string)))
    n = find(strcmp(lab_string,labs)); % find index of node, which
    % contains the used name
    if n
        label(g, n, [lab_string '1']); % add a '1' to the unnumbered name
        labs = get_label(g);
    end
    for i=1:nv(g)
        % check
        if strmatch(strcat(lab_string, num2str(i)),labs,'exact') % check if current number 'i' is available
            continue;
        else
           lab_string = strcat(lab_string, num2str(i)); % if 'i' isn't contained, take this for the new name
           break; % if a "free" name was discovered, quit the for-loop
        end
    end
end
label(g, new_vertex, lab_string);
% Get number of template name from list
n_template = get(handles.selector_dynamic, 'Value');
n_valueSet = get(handles.selector_valueSet, 'Value');
templates{nv(g),1} = template_list{n_template,1};
templates{nv(g),2} = template_list{n_template,4}(n_valueSet);
if ~isfield(templates{nv(g),2},'setName') || isempty(templates{nv(g),2}.setName)
    temp = get(handles.selector_valueSet,'String');
    templates{nv(g),2}.setName = temp{n_valueSet};
end
length_nodeColor = size(data.nodeColor,1);
tempNodeColor = data.nodeColor;
data.nodeColor = cell(length_nodeColor+1,2);
for i = 1:length_nodeColor
   data.nodeColor(i,:) = tempNodeColor(i,:);
end
% this line sets the face color for the node
data.nodeColor{length_nodeColor+1,1} = template_list{n_template,2};
data.nodeColor{length_nodeColor+1,2} = template_list{n_template,3};
%Now, after the node was created, the printCell can be added
length_cellPrint = size(printCell,1);
%Keep the informations of the old nodes
tempCell = printCell;
printCell = cell(length_cellPrint+1,2);
for i = 1:length_cellPrint
    printCell(i,:) = tempCell(i,:);
end
%Initially, the printVector and the plotParams are the same for all templates
statesDim = templates{nv(g),2}.dimension.states;
outputDim = templates{nv(g),2}.dimension.outputs;
printVector = zeros(1,outputDim + statesDim);
printVector(1:outputDim) = ones(1:outputDim)*plotAllOutput;
printCell(length_cellPrint+1,1) = num2cell(printVector,2);
printCell{length_cellPrint+1,2} = initPlotParams(outputDim);
setappdata(handles.figure1,'appData',data);
if graph_refresh == 1
    refresh_graph(0, eventdata, handles,hObject);
end
% store changed data back to structure 'data'
data.g = g;
data.graph_refresh = graph_refresh;
data.templates = templates;
data.template_list = template_list;
data.printCell = printCell;
data.plotAllOutput = plotAllOutput;
data.expSucc = 0;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
computeInputSizes(handles);
% --- Executes when user attempts to close figure1.
function figure1_CloseRequestFcn(hObject, eventdata, handles)
% hObject    handle to figure1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% load application data
data = getappdata(handles.figure1,'appData');
save_settings(['resources' filesep 'lastset'],handles);
filename = 'lastgraph.mat';
pathname = [pwd filesep 'resources' filesep];
saveGraph(hObject, eventdata, handles, pathname, filename);
data = getappdata(handles.figure1,'appData');
% Hint: delete(hObject) closes the figure
%global g;
g = data.g;
free(g)
graph_destroy;
%store application data
data.g = g;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
% graph_destroy();
delete(hObject);
% --- Executes on button press in addconnection.
function addconnection_Callback(hObject, eventdata, handles)
% hObject    handle to addconnection (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
modus = data.modus;
% Fix connections
% Search labels
label1 = get(handles.fromnode,'String');
label2 = get(handles.tonode,'String');
if (get(handles.label_button,'Value') == get(handles.label_button,'Max'))
    labs = get_label(g);
    n1 = strmatch(label1, labs, 'exact');
    n2 = strmatch(label2, labs, 'exact');
else
    n1 = str2num(label1);
    n2 = str2num(label2);
end
switch modus
    case 'undirected';
        add(g,n1(1), n2(1));
        refresh_graph(0, eventdata, handles,hObject);
    case 'directed';
        add(g,n1(1), n2(1),1);
        refresh_graph(0, eventdata, handles,hObject);
end
%refresh_graph(0, eventdata, handles,hObject);
%store application data
data.modus = modus;
data.g = g;
setappdata(handles.figure1,'appData', data);
guidata(hObject, handles);
computeInputSizes(handles);
% --- Executes during object creation, after setting all properties.
function fromnode_CreateFcn(hObject, eventdata, handles)
% hObject    handle to fromnode (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes during object creation, after setting all properties.
function tonode_CreateFcn(hObject, eventdata, handles)
% hObject    handle to tonode (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on button press in randomconnection.
function randomconnection_Callback(hObject, eventdata, handles)
% hObject    handle to randomconnection (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
modus = data.modus;
switch modus
    case 'undirected';
        dir = 0;
    case 'directed';
        dir = 1;
end
a = ceil(nv(g)*rand());
b = floor(nv(g)*rand());
add(g,a,b,dir);
%store application data
data.modus = modus;
data.g = g;
setappdata(handles.figure1,'appData', data);
guidata(hObject, handles);
refresh_graph(0, eventdata, handles,hObject);
computeInputSizes(handles);
% --- Executes on button press in removeconnection.
function removeconnection_Callback(hObject, eventdata, handles)
% hObject    handle to removeconnection (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
data = getappdata(handles.figure1,'appData');
g = data.g;
modus = data.modus;
% Arreglar conexiones
% Buscar en labels
label1 = get(handles.fromnode,'String');
label2 = get(handles.tonode,'String');
%the radio buttons "Label" and "Node number" evaluates, if a node is
%adressed via its number or label
if (get(handles.label_button,'Value') == get(handles.label_button,'Max'))
    %if this is true, the radio button is selected
    labs = get_label(g);
    %n1 = strmatch(label1, labs, 'exact');
    n1 = find(strcmp(label1, labs));
    %n2 = strmatch(label2, labs, 'exact');
    n2 = find(strcmp(label2, labs));
elseif (get(handles.number_button,'Value') == get(handles.label_button,'Max'))
    n1 = str2num(label1);
    n2 = str2num(label2);
end
switch modus
    case 'undirected';
        delete(g,n1(1),n2(1));
    case 'directed';
        dir = 1;
        delete(g,n1(1), n2(1), dir);
end
%store application data
data.g = g;
data.modus = modus;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
refresh_graph(0, eventdata, handles,hObject);
computeInputSizes(handles);
% --- Executes during object creation, after setting all properties.
function remnode_CreateFcn(hObject, eventdata, handles)
% hObject    handle to remnode (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: edit controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --- Executes on button press in removenode.
function removenode_Callback(hObject, eventdata, handles)
% hObject    handle to removenode (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
templates = data.templates;
printCell = data.printCell;
a = str2num(get(handles.remnode,'String'));
if nv(g) && (a <= nv(g))
    templates(a,:) = []; % Deleting the template for the node, which should be deleted
    delete(g,a);
    %Here, the i-th entry of the printCell must be deleted too
    length_printCell = size(printCell,1);
    temp_printCell = printCell;
    printCell = cell(length_printCell-1,2);
    for i = 1:(a-1)
        printCell(i,:) = temp_printCell(i,:);
    end
    for i = (a+1):length_printCell
        printCell(i-1,:) = temp_printCell(i,:);
    end
    refresh_graph(0, eventdata, handles,hObject);
end
%store application data
data.g = g;
data.templates = templates;
data.printCell = printCell;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
computeInputSizes(handles);
% --- Executes on button press in trimgraph.
function trimgraph_Callback(hObject, eventdata, handles)
% hObject    handle to trimgraph (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
trim(data.g);
%store application data
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
refresh_graph(0, eventdata, handles,hObject);
% --- Executes on button press in clearconnections.
function clearconnections_Callback(hObject, eventdata, handles)
% hObject    handle to clearconnections (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
%global g;
clear_edges(g);
%store application data
data.g = g;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
refresh_graph(0, eventdata, handles,hObject);
% --- Executes on button press in completegraph.
function completegraph_Callback(hObject, eventdata, handles)
% hObject    handle to completegraph (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
complete(g);
%store application data
data.g = g;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
refresh_graph(0, eventdata, handles,hObject);
% --- Executes on button press in randomgraph.
function randomgraph_Callback(hObject, eventdata, handles)
% hObject    handle to randomgraph (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
switch data.modus
    case 'undirected';
        random(data.g,1/2);
    case 'directed';
        random(data.g);
end
%store application data
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
refresh_graph(0, eventdata, handles,hObject)
computeInputSizes(handles);
% --- Executes during object creation, after setting all properties.
function listbox1_CreateFcn(hObject, eventdata, handles)
% hObject    handle to listbox1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    empty - handles not created until after all CreateFcns called
% Hint: listbox controls usually have a white background on Windows.
%       See ISPC and COMPUTER.
if ispc
    set(hObject,'BackgroundColor','white');
else
    set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
end
% --------------------------------------------------------------------
function Newgraph_Callback(hObject, eventdata, handles)
% hObject    handle to Newgraph (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
resize(g,0);
templates = cell(0,1);
%store application data
data.g = g;
data.templates = templates;
setappdata(handles.figure1,'appData',data);
refresh_graph(1, eventdata, handles,hObject);
% --------------------------------------------------------------------
function loadgraph_Callback(hObject, eventdata, handles)
% hObject    handle to loadgraph (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
template_list = data.template_list;
[filename, pathname] = uigetfile(...
{'*.mat;','Graph/Network Files';
   '*.mat','MAT-files (*.mat)'; ...
    '*.*',  'All Files (*.*)'}, ...
   'Open');
if filename
    file = strcat(pathname, filename);
    [pathname, filename, ext] = fileparts(file);
    free(g);
    if strcmp(ext, '.mat')
        S = load(file, 'nverts', 'nedges','adj_matrix', 'XY', 'labs', 'templates',...
            'printCell','template_list','modus','nodeColor') ;
        %S = load(file, 'data' );
        %data = S.data;
        %assignin('base','data',data);
        nverts = S.nverts;
        adj_matrix = S.adj_matrix;
        XY = S.XY;
        labs = S.labs;
        templates = S.templates;
        template_list = S.template_list;
        data.modus = S.modus;
        data.printCell = S.printCell;
        data.nodeColor = S.nodeColor;
        g = graph(nverts);
        switch data.modus;
            case 'undirected'; dir = 0;
            case 'directed'; dir = 1;
        end
        for i=1:nverts
            label(g,i,labs{i});
            for j=1:nverts
              if adj_matrix(i,j)
                 add(g,i,j,dir);
                 adj_matrix(j,i) = 0;
              end
            end
        end
        embed(g,XY);
    elseif strcmp(ext, '.gr')
        load(g, file);
        templates = cell(0,1);
        % Temporary code...
        n_template = get(handles.selector_dynamic, 'Value'); % Get template name from list
        for i=1:nv(g)
            templates{i,1}=template_list{n_template,1};
        end
    end
end
%set the uipanel according to stored value of "modus"
switch data.modus
    case 'directed'
        set(handles.button_undirected,'Value', 0.0);
        set(handles.button_directed,'Value', 1.0);
    case 'undirected'
        set(handles.button_undirected,'Value', 1.0);
        set(handles.button_directed,'Value', 0.0);
end
%store application data
data.g = g;
data.templates = templates;
data.template_list = template_list;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
refresh_dynamics(eventdata, handles);
refresh_graph(0, eventdata, handles,hObject);
% --------------------------------------------------------------------
function savegraphas_Callback(hObject, eventdata, handles)
% hObject    handle to savegraphas (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
[filename, pathname] = uiputfile(...
{  '*.mat','MAT-files [Prefered] (*.mat)'; ...
   '*.*',  'All Files (*.*)';}, ...
   'Save');
saveGraph(hObject, eventdata, handles, pathname, filename);
% --------------------------------------------------------------------
function aboutmtids_Callback(hObject, eventdata, handles)
% hObject    handle to aboutmtids (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
about_mtids();
% --------------------------------------------------------------------
function labelview_Callback(hObject, eventdata, handles)
% hObject    handle to labelview (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
%global g;
checkstatus = get(hObject,'Check');
if strcmp(checkstatus, 'on')
    set(hObject,'Check','off');
elseif strcmp(checkstatus, 'off')
    set(handles.colorview,'Check','off');
    set(handles.labelview,'Check','on');
    set(handles.numberview,'Check','off');
    set(handles.blankview,'Check','off');
    refresh_graph(0, eventdata, handles,hObject)
end
%store application data
data.g = g;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
% --------------------------------------------------------------------
function colorview_Callback(hObject, eventdata, handles)
% hObject    handle to colorview (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
%global g;
checkstatus = get(hObject,'Check');
if strcmp(checkstatus, 'on')
    set(hObject,'Check','off');
elseif strcmp(checkstatus, 'off')
    set(handles.colorview,'Check','on');
    set(handles.labelview,'Check','off');
    set(handles.numberview,'Check','off');
    set(handles.blankview,'Check','off');
    refresh_graph(0, eventdata, handles,hObject)
end
guidata(hObject, handles);
% --------------------------------------------------------------------
function numberview_Callback(hObject, eventdata, handles)
% hObject    handle to numberview (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
%global g;
checkstatus = get(hObject,'Check');
if strcmp(checkstatus, 'on')
    set(hObject,'Check','off');
elseif strcmp(checkstatus, 'off')
    set(handles.colorview,'Check','off');
    set(handles.labelview,'Check','off');
    set(handles.numberview,'Check','on');
    set(handles.blankview,'Check','off');
    refresh_graph(0, eventdata, handles,hObject)
end
%store application data
data.g = g;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
% --------------------------------------------------------------------
function blankview_Callback(hObject, eventdata, handles)
% hObject    handle to blankview (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
%global g;
checkstatus = get(hObject,'Check');
if strcmp(checkstatus, 'on')
    set(hObject,'Check','off');
elseif strcmp(checkstatus, 'off')
    set(handles.colorview,'Check','off');
    set(handles.labelview,'Check','off');
    set(handles.numberview,'Check','off');
    set(handles.blankview,'Check','on');
    refresh_graph(0, eventdata, handles,hObject);
end
%store application data
data.g = g;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
% --------------------------------------------------------------------
function export_as_layer_2_Callback(hObject, eventdata, handles)
% hObject    handle to export_as_layer_2 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)global g;
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
templates = data.templates;
template_list = data.template_list;
A  = double(matrix(g));
rmxy(g);
embed(g);
xy = getxy(g);
labs = get_label(g);
name =    'untitled';
template =    'LTI';
if nv(g) > 200
    disp('Exporting...may take some time...go get some coffee...');
else
     disp('Exporting...');
end
disp('  ');
%function contained in folder "interface2simulink"
exportLayer2(name,templates,template_list,A, xy, labs);
if nv(g) > 50
    disp('Done exporting');
    disp(' ');
    %msgbox('Done exporting','Export to Simulink');
else
    disp('Done exporting');
end
%store application data
data.g = g;
data.templates = templates;
data.template_list = template_list;
setappdata(handles.figure1,'appData',data);
guidata(hObject, handles);
function refresh_graph(reset, eventdata, handles,hObject)
% This function refreshes the graph window
%load application data
data = getappdata(handles.figure1,'appData');
g = data.g;
modus = data.modus;
% Check which kind of lable is activated
checklabel = get(handles.labelview,'Check');
checknumber = get(handles.numberview,'Check');
%checkcolor = get(handles.colorview,'Check');
checkblank = get(handles.blankview,'Check');
% rmxy(g);
cla;
if reset == 1
    rmxy(g); %rmxy: erase g's embedding
end
switch modus
    case 'undirected';
        dir = 0;
        if(ne(g)>0) %check if there are vertices in the current graph
            basic_stats(eventdata, handles);
        else
            set(handles.text22,'String', 'Independent Graphs:');
            set(handles.connected_graphs,'String', '0');
            set(handles.text32,'String',' ');
            set(handles.strong_connections,'String', ' ');
            set(handles.text16,'String', 'Graph density:');
            set(handles.graph_density,'String', '0');
            set(handles.text10,'String', 'Average degree:');
            set(handles.average_degree,'String', '0');
            set(handles.text11,'String', 'Median degree:');
            set(handles.median_degree,'String', '0');
            set(handles.text9,'String', 'Minimum degree:');
1000             set(handles.minimum_degree,'String', '0');
1001             set(handles.text12,'String', 'Maximum degree:');
1002             set(handles.maximum_degree,'String', '0');
1003             set(handles.text18,'String', 'Graph heterogenity:');
1004             set(handles.graph_heterogenity,'String', '0');
1005             set(handles.text19,'String', 'Algebraic connectivity:');
1006             set(handles.algebraic_connectivity,'String', '0');
1007         end
1008
1009     case 'directed';
1010         dir = 1;
1011         % do something with the basic stats stuff
1012         if(ne(g)>0) %check if there are vertices in the current graph
1013             basic_stats(eventdata, handles);
1014         else
1015             set(handles.text32,'String','Strong connected subgraphs:');
1016             set(handles.strong_connections,'String', '0');
1017             set(handles.text22,'String', 'Weak connected subgraphs:');
1018             set(handles.connected_graphs,'String', '0');
1019             set(handles.text9,'String', 'Minimum In-Degree:');
1020             set(handles.minimum_degree,'String', '0');
1021             set(handles.text10,'String', 'Maximum In-Degree: ');
1022             set(handles.average_degree,'String', '0');
1023             set(handles.text11,'String', 'Minimum Out-Degree:');
1024             set(handles.median_degree,'String', '0');
1025             set(handles.text12,'String', 'Maximum Out-Degree:');
1026             set(handles.maximum_degree,'String', '0');
1027             set(handles.text16,'String', 'Average Degree:');
1028             set(handles.graph_density,'String', '0');
1029             set(handles.text18,'String', 'Graph is balanced:');
1030             set(handles.graph_heterogenity,'String', '-');
1031             set(handles.text19,'String', 'Has cycles:');
1032             set(handles.algebraic_connectivity,'String', '-');
1033         end
1034 end
1035 % set node color
1036
1037 % check for choice of vertex-layout
1038 if strcmp(checklabel, 'on')
1039     ldraw(g,dir,'-',data.nodeColor(:,1), data.nodeColor(:,2));
1040 %elseif strcmp(checkcolor, 'on')
1041 %    cdraw(g,dir);
1042 elseif strcmp(checknumber, 'on')
1043     ndraw(g,dir,'-',data.nodeColor(:,1), data.nodeColor(:,2));
1044 else
1045     draw(g,dir,'-',data.nodeColor(:,1), data.nodeColor(:,2));
1046 end
1047 set(handles.nedges,'String', num2str(ne(g,dir)));
1048 set(handles.nvertices,'String',num2str(nv(g)));
1049 %store application data
1050 data.g = g;
1051 setappdata(handles.figure1,'appData',data);
1052 % If graph changed, input sizes of nodes must be computed newly
1053 guidata(hObject, handles);
1054 % computeInputSizes(handles);
1055
1056
1057 % --- Executes on button press in laplacianvisualize.
1058 function basic_stats(eventdata, handles)
1059 % hObject    handle to laplacianvisualize (see GCBO)
1060 % eventdata  reserved - to be defined in a future version of MATLAB
1061 % handles    structure with handles and user data (see GUIDATA)
1062
1063 %load application data
1064 data = getappdata(handles.figure1,'appData');
1065 g = data.g;
1066 modus = data.modus;
1067
1068 switch modus
1069     case 'undirected';
1070         L = laplacian(g);
1071         rank_L = rank(L);       % Matrix rank
1072         dim_L  = mean(size(L)); % Matrix dimension
1073         null_L = dim_L - rank(L); %Rank of the null-space (from rank-nullity theorem)
1074                                     %Gives us number of connected (sub) graphs
1075         degree_vector = diag(L);
1076         D = diag(diag(L));
1077         A = D - L; % Adjacency matrix
1078         rank_A = rank(A);       % Matrix rank
1079         dim_A  = mean(size(A)); % Matrix dimension
1080         null_A = dim_A - rank(A); %Rank of the null-space (from rank-nullity theorem)
1081                                     %Gives us number of connected (sub) graphs
1082         set(handles.text22,'String', 'Independent Graphs:');
1083         set(handles.connected_graphs,'String', num2str(null_L,'%d'));
1084         set(handles.text32,'String',' ');
1085         set(handles.strong_connections,'String', ' ');
1086         set(handles.text16,'String', 'Graph density:');
1087         graph_density = mean(degree_vector)/(dim_L-1); %(1)
1088         set(handles.graph_density,'String', num2str(graph_density, '%1.3f'));
1089         graph_average_degree = mean(degree_vector);
1090         set(handles.text10,'String', 'Average degree:');
1091         set(handles.average_degree,'String', num2str(graph_average_degree, '%3.2f'));
1092         set(handles.text11,'String', 'Median degree:');
1093         graph_median_degree = median(degree_vector);
1094         set(handles.median_degree,'String', num2str(graph_median_degree));
1095         graph_min_degree = min(degree_vector);
1096         set(handles.text9,'String', 'Minimum degree:');
1097         set(handles.minimum_degree,'String', num2str(graph_min_degree));
1098         graph_max_degree = max(degree_vector);
1099         set(handles.text12,'String', 'Maximum degree:');
1100         set(handles.maximum_degree,'String', num2str(graph_max_degree));
1101         %graph_density = 2*NEdges/(NVertex*(NVertex-1)); % Segun Wikipedia
1102         graph_heterogenity = sqrt(var(degree_vector))/mean(degree_vector);
1103         set(handles.text18,'String', 'Graph heterogenity:');
1104         set(handles.graph_heterogenity,'String', num2str(graph_heterogenity,'%1.3f'));
1105         [Eigen_Matrix_L, Eigen_Values_L] = eig(L);
1106         [Eigen_Matrix_A, Eigen_Values_A] = eig(A);
1107
1108         % Sorting Eigenvalues
1109         Eigen_Values_L = diag(Eigen_Values_L);
1110         [Eigen_Values_L, ndx] = sort(Eigen_Values_L, 'ascend');
1111         Eigen_Matrix_L=Eigen_Matrix_L(:,ndx);
1112
1113         Eigen_Values_A = diag(Eigen_Values_A);
1114         [Eigen_Values_A, ndx] = sort(Eigen_Values_A, 'ascend');
1115         Eigen_Matrix_A=Eigen_Matrix_A(:,ndx);
1116
1117         graph_connectivityA = Eigen_Values_A(null_L+1);
1118         graph_connectivity = Eigen_Values_L(null_L+1);
1119         set(handles.text19,'String', 'Algebraic connectivity:');
1120         set(handles.algebraic_connectivity,'String', num2str(graph_connectivity));
1121         fiedler_vector   = Eigen_Matrix_L(:,null_L+1);
1122
1123         estrada_connectivity = diag(exp(A));
1124
1125         estrada_graph_index  = trace(exp(A));
1126
1127     case 'directed';
1128         [InDeg OutDeg]=getDegree(matrixOfGraph(g));
1129         LaplacianIn = diag(InDeg) - double(matrixOfGraph(g));
1130         LaplacianOut = diag(OutDeg) - double(matrixOfGraph(g));
1131         rank_L_In = rank(LaplacianIn); %rank of laplacian with indegree
1132         rank_L_Out = rank(LaplacianOut); %rank of laplacian with outdegree
1133         dim_L = mean(size(LaplacianIn)); %matrix-dimension
1134
1135         set(handles.text22,'String', 'Weak connected subgraphs:');
1136         set(handles.connected_graphs,'String', num2str(length(compute_WCC(data.g))));
1137
1138         minInDeg = min(InDeg);
1139         maxInDeg = max(InDeg);
1140         minOutDeg = min(OutDeg);
1141         maxOutDeg = max(OutDeg);
1142
1143         [i,j,s]=find(InDeg == OutDeg);
1144
1145         if size(s,1) == dim_L
1146             isBalanced = 'Yes';
1147         else %if size(s,1) < dim_L
1148             isBalanced = 'No';
1149         end
1150         strongCons = num2str(length(compute_SCC(data.g)));
1151
1152         % idea of detecting cyclic graphs: if there are less sets of SCC
1153         % as nodes in the graph, then there must be at least one cycle.
1154         if str2double(strongCons) < nv(data.g)
1155             isCyclic = 'Yes';
1156         else
1157             isCyclic = 'No';
1158         end
1159         set(handles.text32,'String','Strong connected subgraphs:');
1160         set(handles.strong_connections,'String', strongCons);
1161         set(handles.text9,'String', 'Minimum In-Degree:');
1162         set(handles.minimum_degree,'String', num2str(minInDeg,'%d'));
1163         set(handles.text10,'String', 'Maximum In-Degree:');
1164         set(handles.average_degree,'String', num2str(maxInDeg,'%d'));
1165         set(handles.text11,'String', 'Minimum Out-Degree:');
1166         set(handles.median_degree,'String', num2str(minOutDeg,'%d'));
1167         set(handles.text12,'String', 'Maximum Out-Degree:');
1168         set(handles.maximum_degree,'String', num2str(maxOutDeg,'%d'));
1169         set(handles.text16,'String', 'Average Degree:');
1170         set(handles.graph_density,'String', num2str(mean(InDeg), '%1.3f'));
1171         set(handles.text18,'String', 'Graph is balanced:');
1172         set(handles.graph_heterogenity,'String', isBalanced);
1173         set(handles.text19,'String', 'Has cycles:');
1174         set(handles.algebraic_connectivity,'String', isCyclic);
1175 end
1176 %no data storaged needed, because this is a "void" function
1177
1178
1179 % --- Executes during object creation, after setting all properties.
1180 function dynamic_label_CreateFcn(hObject, eventdata, handles)
1181 % hObject    handle to dynamic_label (see GCBO)
1182 % eventdata  reserved - to be defined in a future version of MATLAB
1183 % handles    empty - handles not created until after all CreateFcns called
1184
1185 % Hint: edit controls usually have a white background on Windows.
1186 %       See ISPC and COMPUTER.
1187 if ispc
1188     set(hObject,'BackgroundColor','white');
1189 else
1190     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1191 end
1192
1193
1194 % --------------------------------------------------------------------
1195 function import_from_simulink_Callback(hObject, eventdata, handles)
1196 % hObject    handle to import_from_simulink (see GCBO)
1197 % eventdata  reserved - to be defined in a future version of MATLAB
1198 % handles    structure with handles and user data (see GUIDATA)
1199
1200 %load application data
1201 data = getappdata(handles.figure1,'appData');
1202 g = data.g;
1203 template_list = data.template_list;
1204 templates = data.templates;
1205
1206 [filename, pathname] = uigetfile(...
1207 {'*.mdl','Simulink Model (*.mdl)';
1208    '*.*',  'All Files (*.*)'}, ...
1209    'Import Simulink model');
1210
1211 file = strcat(pathname, filename);
1212
1213 addpath(pathname);
1214
1215 [pathname, model, ext] = fileparts(file);
1216
1217 [A, nverts, nedges, xy, labs ] = importSimulink(model);
1218
1219 % Delete graph!
1220
1221 % Deprecated! elist = adj_to_elist(A);
1222
1223 free(g);
1224
1225 g = graph(nverts);
1226
1227 % Preliminary template import
1228 n_template = get(handles.selector_dynamic, 'Value'); % Get template name from list
1229
1230 for i=1:nverts
1231     label(g,i,labs{i});
1232     templates{i,1}=template_list{n_template,1};
1233     for j=1:nverts
1234         if A(i,j)
1235              add(g,i,j);
1236              A(j,i) = 0;
1237         end
1238     end
1239 end
1240
1241 embed(g,xy);
1242
1243 %store application data
1244 data.g = g;
1245 data.template_list = template_list;
1246 data.templates = templates;
1247 setappdata(handles.figure1,'appData',data);
1248 guidata(hObject, handles);
1249 refresh_graph(0, eventdata, handles,hObject);
1250
1251
1252 % --------------------------------------------------------------------
1253 function export_to_simulink_Callback(hObject, eventdata, handles)
1254 % hObject    handle to export_to_simulink (see GCBO)
1255 % eventdata  reserved - to be defined in a future version of MATLAB
1256 % handles    structure with handles and user data (see GUIDATA)
1257
1258 %load application data
1259 data = getappdata(handles.figure1,'appData');
1260 g = data.g;
1261 template_list = data.template_list;
1262 templates = data.templates;
1263 disp('Export mode 1');
1264 A  = double(matrix(g));
1265
1266 % Makes the graph a circle
1267 rmxy(g);
1268 embed(g);
1269
1270 xy = getxy(g);
1271
1272 labs = get_label(g);
1273 name =    'untitled';
1274 template =    'LTI';
1275 if nv(g) > 200
1276     disp('Exporting...may take some time...go get some coffee...');
1277 else
1278     disp('Exporting...');
1279 end
1280 disp('  ');
1281
1282 exportSimulink(name,templates,template_list,A, xy, labs);
1283
1284 if nv(g) > 50
1285     disp('Done exporting');
1286     disp(' ');
1287     %msgbox('Done exporting','Export to Simulink');
1288 else
1289     disp('Done exporting');
1290 end
1291 %no app data storage needed, because this can be seen as a "void" function.
1292
1293
1294 % --- Executes on button press in add_multiple_nodes.
1295 function add_multiple_nodes_Callback(hObject, eventdata, handles)
1296 % hObject    handle to add_multiple_nodes (see GCBO)
1297 % eventdata  reserved - to be defined in a future version of MATLAB
1298 % handles    structure with handles and user data (see GUIDATA)
1299
1300 %load application data
1301 data = getappdata(handles.figure1,'appData');
1302 n_nodes = str2num(get(handles.number_of_nodes,'String'));
1303 % this is needed, because during creation of the nodes the graph isn't build
1304 % newly; only at the end the graph should built new.
1305 data.graph_refresh = 0;
1306 setappdata(handles.figure1,'appData',data);
1307 for i=1:n_nodes
1308    newnode_Callback(hObject, eventdata, handles);
1309 end
1310 data = getappdata(handles.figure1,'appData');
1311 %store application data
1312 data.graph_refresh = 1;
1313 setappdata(handles.figure1,'appData',data);
1314 refresh_graph(0, eventdata, handles, hObject);
1315
1316
1317 % --------------------------------------------------------------------
1318 function exit_to_matlab_Callback(hObject, eventdata, handles)
1319 % hObject    handle to exit_to_matlab (see GCBO)
1320 % eventdata  reserved - to be defined in a future version of MATLAB
1321 % handles    structure with handles and user data (see GUIDATA)
1322 close(handles.output);
1323
1324 % --- Executes during object creation, after setting all properties.
1325 function number_of_nodes_CreateFcn(hObject, eventdata, handles)
1326 % hObject    handle to number_of_nodes (see GCBO)
1327 % eventdata  reserved - to be defined in a future version of MATLAB
1328 % handles    empty - handles not created until after all CreateFcns called
1329
1330 % Hint: edit controls usually have a white background on Windows.
1331 %       See ISPC and COMPUTER.
1332 if ispc
1333     set(hObject,'BackgroundColor','white');
1334 else
1335     set(hObject,'BackgroundColor',get(0,'defaultUicontrolBackgroundColor'));
1336 end
1337
1338
1339 % --- Executes on button press in label_button.
1340 function label_button_Callback(hObject, eventdata, handles)
1341 % hObject    handle to label_button (see GCBO)
1342 % eventdata  reserved - to be defined in a future version of MATLAB
1343 % handles    structure with handles and user data (see GUIDATA)
1344 % Hint: get(hObject,'Value') returns toggle state of label_button
1345 set(handles.number_button,'Value', 0);
1346 set(handles.label_button,'Value', 1);
1347
1348
1349 % --- Executes on button press in number_button.
1350 function number_button_Callback(hObject, eventdata, handles)
1351 % hObject    handle to number_button (see GCBO)
1352 % eventdata  reserved - to be defined in a future version of MATLAB
1353 % handles    structure with handles and user data (see GUIDATA)
1354 % Hint: get(hObject,'Value') returns toggle state of number_button
1355 set(handles.label_button,'Value', 0);
1356 set(handles.number_button,'Value', 1);
1357
1358
1359 % --------------------------------------------------------------------
1360 function export_to_workplace_Callback(hObject, eventdata, handles)
1361 % hObject    handle to export_to_workplace (see GCBO)
1362 % eventdata  reserved - to be defined in a future version of MATLAB
1363 % handles    structure with handles and user data (see GUIDATA)
1364 %load application data
1365 data = getappdata(handles.figure1,'appData');
1366 g = data.g;
1367 modus = data.modus;
1368 uiwait(export_as_matrix(laplacian(g),g,modus));
1369
1370
1371 % --------------------------------------------------------------------
1372 function import_from_workplace_Callback(hObject, eventdata, handles)
1373 % hObject    handle to import_from_workplace (see GCBO)
1374 % eventdata  reserved - to be defined in a future version of MATLAB
1375 % handles    structure with handles and user data (see GUIDATA)
1376
1377 %load application data
1378 data = getappdata(handles.figure1,'appData');
1379 g = data.g;
1380 templates = data.templates;
1381 template_list = data.template_list;
1382 modus = data.modus;
1383 %printCell = data.printCell;
1384
1385 prompt = {'Workspace:','Variable name:'};
1386 dlg_title = 'Inport matrix from workspace';
1387 num_lines = 1;
1388 def = {'base','matrix'};
1389 answer = inputdlg(prompt,dlg_title,num_lines,def);
1390
1391 if ~isempty(answer)
1392     M = evalin(answer{1},answer{2});
1393     switch modus
1394         case 'undirected';
1395             elist = any_matrix_to_elist(M);
1396         case 'directed';
1397             elist = any_matrix_to_elist(M,1);
1398     end
1399     %Corrects the problem posed by a zero-adj-matrix!
1400     if (elist(1,:) == zeros(1,2))
1401         g = graph(size(M,1));
1402     else
1403         switch modus
1404             case 'undirected';
1405                 g = graph(elist);
1406             case 'directed';
1407                 maxM = max(M);
1408                 g = graph(maxM(1));
1409                 for i = 1:length(elist)
1410                     add(g,elist(i,1),elist(i,2),1);
1411                 end
1412         end
1413     end
1414     templates = cell(0,1);
1415     n_template = get(handles.selector_dynamic, 'Value'); % Get template name from list
1416     for i=1:nv(g)
1417         templates{i,1}=template_list{n_template,1};
1418     end
1419 end
1420 %Initialize the printCell
1421 nrNodes = nv(g);
1422 printCell = cell(nrNodes,2);
1423 for i = 1:nrNodes
1424     printCell(i,1) = num2cell([1 0],2);
1425     printCell{i,1} = initPlotParams;
1426 end
1427 %store application data
1428 data.g = g;
1429 data.templates = templates;
1430 data.template_list = template_list;
1431 data.modus = modus;
1432 data.printCell = printCell;
1433 setappdata(handles.figure1,'appData',data);
1434 guidata(hObject, handles);
1435 refresh_graph(0, eventdata, handles,hObject);
1436
1437
1438 % --------------------------------------------------------------------
1439 function add_mdl_template_Callback(hObject, eventdata, handles)
1440 % hObject    handle to add_mdl_template (see GCBO)
1441 % eventdata  reserved - to be defined in a future version of MATLAB
1442 % handles    structure with handles and user data (see GUIDATA)
1443 %load application data
1444 data = getappdata(handles.figure1,'appData');
1445 template_list = data.template_list;
1446 templates = data.templates;
1447
1448 oldFolder = cd(strcat(pwd,'/templates'));
1449
1450 [filename, pathname] = uigetfile(...
1451 {'*.mdl','Simulink model template(*.mdl)';
1452    '*.*',  'All Files (*.*)'}, ...
1453    'Import Simulink model templates', ...
1454    'MultiSelect', 'on');
1455
1456 if iscell(filename)
1457     [a, b] = size(filename);
1458     for i=1:b
1459         file = strcat(pathname, filename{i});
1460         [path, template, ext] = fileparts(file);
1461         if strcmp('.mdl', ext)
1462             if strmatch(template, template_list, 'exact')
1463                 disp(strcat('WARNING: A template with the name "', template, '" was already imported!'));
1464                 continue;
1465             else
1466                 [ny, nx] = size(template_list);
1467                 template_list{ny+1,1} = template;
1468                 template_list{ny+1,2} = [1 1 1]; %default color
1469                 template_list{ny+1,3} = [0 0 1]; %default color
1470             end
1471         else
1472             disp(strcat('ERROR: "',filename{i}, '" is not a Simulink model'));
1473         end
1474     end % End del for
1475 elseif filename %filename is not a cell (it's a string) and not 0
1476     file = strcat(pathname, filename);
1477     [path, template, ext] = fileparts(file);
1478     if strcmp('.mdl', ext)
1479         if strmatch(template, template_list{:,1}, 'exact')
1480             disp(strcat('WARNING: A template with the name "', template, '" was already imported!'));
1481         else
1482             [ny, nx] = size(template_list);
1483             template_list{ny+1,1} = template;
1484             template_list{ny+1,2} = [1 1 1]; %default color
1485             template_list{ny+1,3} = [0 0 1]; %default color
1486         end
1487     else
1488         disp(strcat('ERROR: "',filename, '" is not a Simulink model'));
1489     end
1490 end
1491 cd(oldFolder);
1492 %store application data
1493 data.template_list = template_list;
1494 setappdata(handles.figure1,'appData',data);
1495 refresh_dynamics(eventdata, handles);
1496 guidata(hObject, handles);
1497
1498
1499
1500 % --- Executes during object creation, after setting all properties.
1501 function selector_dynamic_CreateFcn(hObject, eventdata, handles)
1502 % hObject    handle to selector_dynamic (see GCBO)
1503 % eventdata  reserved - to be defined in a future version of MATLAB
1504 % handles    empty - handles not created until after all CreateFcns called
1505
1506 % Hint: popupmenu controls usually have a white background on Windows.
1507 %       See ISPC and COMPUTER.
1508 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1509     set(hObject,'BackgroundColor','white');
1510 end
1511
1512
1513 % --- Executes on selection change in selector_dynamic.
1514 function selector_dynamic_Callback(hObject, eventdata, handles)
1515 % hObject    handle to selector_dynamic (see GCBO)
1516 % eventdata  reserved - to be defined in a future version of MATLAB
1517 % handles    structure with handles and user data (see GUIDATA)
1518 % Hints: contents = cellstr(get(hObject,'String')) returns selector_dynamic contents as cell array
1519 %        contents{get(hObject,'Value')} returns selected item from selector_dynamic
1520 %get(hObject,'Value')
1521 refresh_valueSet(handles);
1522
1523 % --- Executes during object creation, after setting all properties.
1524 function selector_valueSet_CreateFcn(hObject, eventdata, handles)
1525 % hObject    handle to selector_valueSet (see GCBO)
1526 % eventdata  reserved - to be defined in a future version of MATLAB
1527 % handles    empty - handles not created until after all CreateFcns called
1528
1529 % Hint: popupmenu controls usually have a white background on Windows.
1530 %       See ISPC and COMPUTER.
1531 if ispc && isequal(get(hObject,'BackgroundColor'), get(0,'defaultUicontrolBackgroundColor'))
1532     set(hObject,'BackgroundColor','white');
1533 end
1534
1535
1536 function refresh_dynamics(eventdata, handles)
1537 % This function refreshes the drop down menu of the dynamic templates
1538 %load application data
1539 data = getappdata(handles.figure1,'appData');
1540 template_list = data.template_list;
1541 [ny, nx] = size(template_list);
1542 for i=1:ny
1543     if i == 1
1544         drop_string = template_list{1,1};
1545     elseif i == ny
1546         drop_string = strcat(drop_string,'|',template_list{i,1});
1547     else
1548         drop_string = strcat(drop_string,'|',template_list{i,1});
1549     end
1550 end
1551 set(handles.selector_dynamic, 'String', drop_string);
1552 refresh_valueSet(handles);
1553 %guidata(hObject, handles);
1554 %no data storage needed, because this can be seen as a "void" function.
1555
1556 function refresh_valueSet(handles)
1557 % This function refreshes the drop down menu of the parameter value sets
1558 % for the dynamic templates
1559 %load application data
1560 data = getappdata(handles.figure1,'appData');
1561 %Check which template is chosen
1562 idxDynSelector = get(handles.selector_dynamic,'Value');
1563 stringDynSelector = get(handles.selector_dynamic,'String');
1564 % Choose param struct
1565 temp = ~cellfun(@isempty, regexp(data.template_list(:,1), ...
1566     regexp(stringDynSelector(idxDynSelector,:),'\w+','match')));
1567 nrOfParamSets = length(data.template_list{temp,4});
1568 % drop_string = cell(nrOfParamSets,1);
1569 counter = 0;
1570 for i=1:nrOfParamSets
1571     if data.template_list{idxDynSelector,4}(i).isActive
1572         counter = counter + 1;
1573         % Check if template contains a name for a set
1574         if isfield(data.template_list{idxDynSelector,4}(i),'setName') &&...
1575                 ~isempty(data.template_list{idxDynSelector,4}(i).setName)
1576             drop_string{counter} = data.template_list{idxDynSelector,4}(i).setName; %#ok<AGROW>
1577         else
1578             drop_string{counter} = ['Value set ' num2str(i)]; %#ok<AGROW>
1579         end
1580     end
1581 end
1582 set(handles.selector_valueSet, 'String', drop_string,'Value',1);
1583
1584
1585 % --- Executes on button press in circular_graph.
1586 function circular_graph_Callback(hObject, eventdata, handles)
1587 % hObject    handle to circular_graph (see GCBO)
1588 % eventdata  reserved - to be defined in a future version of MATLAB
1589 % handles    structure with handles and user data (see GUIDATA)
1590
1591 %load application data
1592 data = getappdata(handles.figure1,'appData');
1593 g = data.g;
1594 modus = data.modus;
1595
1596 switch modus
1597     case 'undirected';
1598         dir = 0;
1599     case 'directed';
1600         dir = 1;
1601 end
1602
1603 clear_edges(g);
1604
1605 for i=1:(nv(g)-1)
1606     add(g,i,i+1,dir);
1607 end
1608 add(g,nv(g),1,dir)
1609
1610 %store application data
1611 data.g = g;
1612 data.modus = modus;
1613 setappdata(handles.figure1,'appData',data);
1614 guidata(hObject, handles);
1615 refresh_graph(0, eventdata, handles,hObject);
1616
1617
1618
1619 % --- Executes on mouse press over figure background, over a disabled or
1620 % --- inactive control, or over an axes background.
1621 function figure1_WindowButtonDownFcn(hObject, eventdata, handles)
1622 % hObject    handle to figure1 (see GCBO)
1623 % eventdata  reserved - to be defined in a future version of MATLAB
1624 % handles    structure with handles and user data (see GUIDATA)
1625
1626 %load application data
1627 data = getappdata(handles.figure1,'appData');
1628 g = data.g;
1629 botton_down = data.botton_down;
1630 move_index = data.move_index;
1631 start_index = data.start_index;
1632 templates = data.templates;
1633 template_list = data.template_list;
1634 modus = data.modus;
1635 printCell = data.printCell;
1636
1637 CP = get(handles.axes1, 'CurrentPoint');
1638 x_c = CP(1,1);
1639 y_c = CP(1,2);
1640
1641 XY = getxy(g);
1642 x = XY(:,1);
1643 y = XY(:,2);
1644
1645 d_x = x-x_c;
1646 d_y = y-y_c;
1647
1648 radius = d_x.*d_x+d_y.*d_y;
1649 [C,I] = min(radius);
1650 if C <= 0.05; % Hardcoded value!
1651
1652     if strcmp(get(handles.output, 'SelectionType'), 'normal')
1653         %  disp(I);
1654         move_index = I;
1655         botton_down = 1;
1656         start_index = 0; % Reset starting index
1657
1658     elseif strcmp(get(handles.output, 'SelectionType'), 'alt')
1659         if start_index
1660             if has(g, start_index, I) %no additional request for the case of directed graphs necessary
1661                 switch modus
1662                     case 'undirected';
1663                         delete(g,start_index, I);
1664                     case 'directed';
1665                         delete(g,start_index, I,1);
1666                 end
1667             else
1668                 switch modus
1669                     case 'undirected';
1670                         add(g,start_index,I);
1671                     case 'directed';
1672                         add(g,start_index,I,1);
1673                 end
1674             end
1675             start_index = 0;
1676             refresh_graph(0, eventdata, handles,hObject);
1677         else
1678             start_index = I;
1679         end
1680
1681     elseif strcmp(get(handles.output, 'SelectionType'), 'open')
1682         % Opens EDIT_NODE(): node modification dialog
1683         [s1,nodenumber,nodelabel,template,neighbours,destroy,templateSaved,...
1684             printVector,plotParams,newTemplate] = edit_node(I, get_label(g,I), ...
1685             templates(I,:), template_list, g(I), printCell(I,:),handles.figure1);
1686         if ~all(cellfun(@isequal,newTemplate,templates(I,:)))
1687             data.expSucc = 0;
1688             data.simOut = [];
1689         end
1690         templates(I,:) = newTemplate;
1691         if destroy == 0
1692             if ~strcmp(nodelabel, get_label(g,I))
1693                 if(strmatch(nodelabel,get_label(g),'exact'))
1694                     for i=1:nv(g)
1695                         if (strmatch(strcat(nodelabel, num2str(i)),get_label(g),'exact'))
1696                             continue;
1697                         else
1698                             nodelabel = strcat(nodelabel, num2str(i));
1699                             break;
1700                         end
1701                     end
1702                 end
1703             end
1704
1705             label(g,I, nodelabel);
1706
1707             templates{I} = template;
1708             e_delete = g(I);
1709             size_ne = size(e_delete,2);
1710
1711             if ~strcmp('double',class(neighbours))
1712                 %disp(['Class of variable "neighbour" is not "double".']);
1713                 neighbours = eval(neighbours); %neighbours must be of type "double"
1714             end
1715
1716             for i=1:size_ne
1717                 delete(g,I,e_delete(i));
1718             end
1719             size_ne = size(neighbours,2);
1720             if ~strcmp(neighbours, '[]')
1721                 for i=1:size_ne
1722                     if strcmp(data.modus,'directed')
1723                         add(g,I,neighbours(i),1);
1724                     else
1725                         add(g,I,neighbours(i));
1726                     end
1727                 end
1728             end
1729             %assignin('base','printVector',printVector);
1730             %Provide here the new plotting information
1731             printCell(nodenumber,1) = num2cell(printVector,2);
1732             printCell{nodenumber,2} = plotParams;
1733             refresh_graph(0, eventdata, handles,hObject);
1734         elseif destroy == 1
1735             if nv(g) && (I <= nv(g))
1736                 templates(I,:) = []; % Deleting a template
1737                 delete(g,I);
1738                 %Here, the i-th entry of the printCell must be deleted too
1739                 if size(printCell,1) == 1
1740                     printCell = cell(0,2);
1741                 else
1742                     length_printCell = size(printCell,1);
1743                     % disp(['Length of printCell: ' num2str(length_printCell) ]);
1744                     temp_printCell = printCell;
1745                     printCell = cell(length_printCell-1,2);
1746                     for i = 1:(nodenumber-1)
1747                         printCell(i,:) = temp_printCell(i,:);
1748                     end
1749                     for i = (nodenumber+1):length_printCell
1750                         printCell(i-1,:) = temp_printCell(i,:);
1751                     end
1752                 end
1753                 refresh_graph(0, eventdata, handles,hObject);
1754             end
1755         end %if destroy == 0
1756         if templateSaved
1757             template_list = readImportedTemplates(template_list);
1758         end
1759         %}
1760     end
1761 else % do nothing?
1762
1763 end
1764
1765 if strcmp(get(handles.output, 'SelectionType'), 'extend')
1766     start_button = 0;
1767     button_down = 0;
1768     newnode_Callback(hObject, eventdata, handles);
1769     data = getappdata(handles.figure1,'appData');
1770     XY(nv(g),1) = x_c;
1771     XY(nv(g),2) = y_c;
1772     embed(g,XY);
1773     refresh_graph(0, eventdata, handles,hObject);
1774     data.g = g;
1775     setappdata(handles.figure1,'appData',data);
1776     guidata(hObject, handles);
1777     return
1778 end
1779
1780 %store application data
1781 data.g = g;
1782 data.templates = templates;
1783 data.botton_down = botton_down;
1784 data.move_index = move_index;
1785 data.start_index = start_index;
1786 data.templates = templates;
1787 data.template_list = template_list;
1788 data.modus = modus;
1789 data.printCell = printCell;
1790 setappdata(handles.figure1,'appData',data);
1791 guidata(hObject, handles);
1792 computeInputSizes(handles);
1793 refresh_valueSet(handles);
1794
1795
1796 % --- Executes on mouse press over figure background, over a disabled or
1797 % --- inactive control, or over an axes background.
1798 function figure1_WindowButtonUpFcn(hObject, eventdata, handles)
1799 % hObject    handle to figure1 (see GCBO)
1800 % eventdata  reserved - to be defined in a future version of MATLAB
1801 % handles    structure with handles and user data (see GUIDATA)
1802
1803 %load application data
1804 data = getappdata(handles.figure1,'appData');
1805 g = data.g;
1806 botton_down = 0;
1807
1808 %store application data
1809 data.g = g;
1810 data.botton_down = botton_down;
1811 setappdata(handles.figure1,'appData',data);
1812 guidata(hObject, handles);
1813
1814 % --- Executes on mouse motion over figure - except title and menu.
1815 function figure1_WindowButtonMotionFcn(hObject, eventdata, handles)
1816 % hObject    handle to figure1 (see GCBO)
1817 % eventdata  reserved - to be defined in a future version of MATLAB
1818 % handles    structure with handles and user data (see GUIDATA)
1819 %load application data
1820 data = getappdata(handles.figure1,'appData');
1821 botton_down = data.botton_down;
1822 move_index = data.move_index;
1823 g = data.g;
1824
1825 if botton_down
1826     CP = get(handles.axes1, 'CurrentPoint');
1827     x_c = CP(1,1);
1828     y_c = CP(1,2);
1829     XY = getxy(g);
1830     XY(move_index,1) = x_c;
1831     XY(move_index,2) = y_c;
1832     embed(g,XY);
1833     refresh_graph(0, eventdata, handles,hObject);
1834 end
1835
1836 %store application data
1837 data.botton_down = botton_down;
1838 data.move_index = move_index;
1839 data.g = g;
1840 setappdata(handles.figure1,'appData',data);
1841 guidata(hObject, handles);
1842
1843
1844 % --------------------------------------------------------------------
1845 function export_as_layer_Callback(hObject, eventdata, handles)
1846 % hObject    handle to export_as_layer (see GCBO)
1847 % eventdata  reserved - to be defined in a future version of MATLAB
1848 % handles    structure with handles and user data (see GUIDATA)
1849
1850 %load application data
1851 data = getappdata(handles.figure1,'appData');
1852 g = data.g;
1853 templates = data.templates;
1854 template_list = data.template_list;
1855
1856 A  = double(matrix(g));
1857 rmxy(g);
1858 embed(g);
1859 xy = getxy(g);
1860
1861 labs = get_label(g);
1862 name =    'untitled';
1863 template ='LTI';
1864 if nv(g) > 200
1865     disp('Exporting...may take some time...go get some coffee...');
1866 else
1867     disp('Exporting...');
1868 end
1869 disp('  ');
1870 exportLayer(name,templates,template_list,A, xy, labs);
1871
1872 if nv(g) > 50
1873     disp('Done exporting');
1874     disp(' ');
1875     %msgbox('Done exporting','Export to Simulink');
1876 else
1877     disp('Done exporting');
1878 end
1879
1880
1881 % --- Executes on button press in update_graph_button.
1882 function update_graph_button_Callback(hObject, eventdata, handles)
1883 % hObject    handle to update_graph_button (see GCBO)
1884 % eventdata  reserved - to be defined in a future version of MATLAB
1885 % handles    structure with handles and user data (see GUIDATA)
1886 refresh_graph(1, eventdata, handles,hObject);
1887
1888
1889 % --------------------------------------------------------------------
1890 function export_to_simulink2_Callback(hObject, eventdata, handles)
1891 % hObject    handle to export_to_simulink2 (see GCBO)
1892 % eventdata  reserved - to be defined in a future version of MATLAB
1893 % handles    structure with handles and user data (see GUIDATA)
1894
1895 %load application data
1896 data = getappdata(handles.figure1,'appData');
1897 g = data.g;
1898 templates = data.templates;
1899 template_list = data.template_list;
1900 % disp('Export mode 2');
1901 A  = double(matrix(g));
1902
1903 % Makes the graph a circle
1904 rmxy(g);
1905 embed(g);
1906 xy = getxy(g);
1907 labs = get_label(g);
1908
1909 % Invoke subroutine which checks the system and its parameters on consistency
1910 check = systemConsistencyTest(handles);
1911
1912 if check
1913     % Determine system name
1914     prompt = {'Enter name of system: '};
1915     dlg_title = 'Name of system';
1916     num_lines = 1;
1917     def = {'untitled'};
1918     name = inputdlg(prompt,dlg_title,num_lines,def);
1919     if isempty(name)
1920         name = def;
1921     end
1922     % template =    'LTI';
1923     if nv(g) > 200
1924         disp('Exporting...this may take some time...');
1925     else
1926         disp('Exporting...');
1927     end
1928     disp('  ');
1929     filename = exportSimulink2(name{:}, templates, template_list, A, xy, labs, data.flag_showSimMod);
1930     disp('Done exporting');
1931     expSucc = 1;
1932 else
1933     disp('System consistency test failed');
1934     expSucc = 0;
1935 end
1936
1937 if expSucc && ~isempty(filename)
1938     data.sysFilename = filename;
1939 end
1940 %store application data
1941 data.expSucc = expSucc;
1942 setappdata(handles.figure1,'appData',data);
1943 guidata(hObject, handles);
1944
1945
1946 % --- Executes when selected object is changed in uipanel9.
1947 function uipanel9_SelectionChangeFcn(hObject, eventdata, handles)
1948 % hObject    handle to the selected object in uipanel9
1949 % eventdata  structure with the following fields (see UIBUTTONGROUP)
1950 %    EventName: string 'SelectionChanged' (read only)
1951 %    OldValue: handle of the previously selected object or empty if none was selected
1952 %    NewValue: handle of the currently selected object
1953 % handles    structure with handles and user data (see GUIDATA)
1954 % Originally taken from the Help Menu "Programming a button group"
1955 % With it, the choice of which graphs are supported can be done
1956
1957 %load application data
1958 data = getappdata(handles.figure1,'appData');
1959
1960 switch get(eventdata.NewValue,'Tag') % Get Tag of selected object.
1961     case 'button_undirected'
1962         data.modus = 'undirected';
1963         qstring = {'Preserve vertices?','(Edges will be deleted in both cases)'};
1964         choice = questdlg(qstring, ...
1965             'Change of graph modus', ...
1966             'Yes','No','No');
1967         switch choice
1968             case 'Yes';
1969                 % Only delete edges
1970                 elist = edges(data.g,1);
1971                 for ii = 1:size(elist,1)
1972                     delete(data.g, elist(ii,1), elist(ii,2), 1);
1973                 end
1974             case 'No';
1975                 % Delete entire graph
1976                 resize(data.g,0);
1977                 data.printCell = cell(0,2);
1978                 data.nodeColor = cell(0,2);
1979         end
1980         guidata(hObject, handles);
1981         refresh_graph(0, eventdata, handles,hObject);
1982     case 'button_directed'
1983         data.modus = 'directed';
1984         qstring = {'Preserve vertices?','(Edges will be deleted in both cases)'};
1985         choice = questdlg(qstring, ...
1986             'Change of graph modus', ...
1987             'Yes','No','No');
1988         switch choice
1989             case 'Yes';
1990                 elist = edges(data.g,0);
1991                 delete(data.g,elist);
1992             case 'No';
1993                 resize(data.g,0);
1994                 data.printCell = cell(0,2);
1995                 data.nodeColor = cell(0,2);
1996         end
1997         guidata(hObject, handles);
1998         refresh_graph(0, eventdata, handles,hObject);
1999     % Continue with more cases as necessary.
2000     otherwise
2001         % Code for when there is no match.
2002         data.modus = 'undirected';
2003 end
2004 %store application data
2005 setappdata(handles.figure1,'appData',data);
2006 guidata(hObject, handles);
2007
2008
2009 % --------------------------------------------------------------------
2010 function run_simulation_Callback(hObject, eventdata, handles)
2011 % hObject    handle to run_simulation (see GCBO)
2012 % eventdata  reserved - to be defined in a future version of MATLAB
2013 % handles    structure with handles and user data (see GUIDATA)
2014
2015 %load application data
2016 data = getappdata(handles.figure1,'appData');
2017 g = data.g;
2018 expSucc = data.expSucc;
2019 printCell = data.printCell;
2020 templates = data.templates;
2021
2022 %global g;
2023 %global printCell;
2024 %global templates;
2025 %global expSucc;
2026
2027 %After export to simulink is complete, start the simulation, using the
2028 %plotting parameters in printCell
2029 if expSucc ~= 1
2030     msgbox('Please start ''Export to Simulink'' before using this function.','Notice');
2031 end
2032
2033 if expSucc == 1
2034     %We need: number of nodes, number of internal states per node
2035     nrNodes = nv(g);
2036     if ~isfield(data,'simOut') || isempty(data.simOut)
2037         simOut = performSimulation(handles);
2038         data.simOut = simOut;
2039     else
2040         simOut = data.simOut;
2041     end
2042
2043     %Plotting of the simulation result can be done on different ways. For now,
2044     %every state gets its own figure
2045     t = simOut.get('tout');
2046     % reshaping the states signals into X(value,noOfStates,noOfNode)
2047     Xtemp = simOut.get('xout');
2048     counter = 1;
2049     X = cell(nrNodes,1);
2050     for i = 1:nrNodes
2051         noOfStates = data.templates{i,2}.dimension.states;
2052         X(i) = { Xtemp(:,counter:counter+noOfStates-1) };
2053         counter = counter + noOfStates;
2054     end
2055     for i = 1:nrNodes
2056         temp = printCell{i,1};
2057         if any(temp)
2058             figure;
2059             hold on;
2060             %Check if output of node i should be plotted
2061             stringMatrix = cell(1,1);
2062             if any(temp(1:data.templates{i,2}.dimension.outputs))
2063                 eval(['y = simOut.get(''nodeout' num2str(i) ''').signals.values;']);
2064                 outputsToPlot = size(y,2);
2065                 for kk = 1:size(y,2)
2066                     plot(t,y(:,kk),...
2067                         'Color',printCell{i,2}(kk).lineColor,...
2068                         'Linewidth',str2num(printCell{i,2}(kk).lineWidth),...
2069                         'LineStyle',printCell{i,2}(kk).lineStyle,...
2070                         'Marker',printCell{i,2}(kk).marker,...
2071                         'MarkerEdgeColor',printCell{i,2}(kk).edgeColor ,...
2072                         'MarkerFaceColor',printCell{i,2}(kk).faceColor); %#ok<*ST2NM>
2073                     stringMatrix{kk} = ['Output signal ' num2str(kk) ' of node ' num2str(i)];
2074                 end
2075             end
2076             %legend(['Output signal of node' num2str(i)]);
2077             counterStringMatrix = outputsToPlot;
2078             for kk = outputsToPlot+1:length(temp)
2079                 if temp(kk)
2080                     counterStringMatrix = counterStringMatrix + 1;
2081                     plot(t,X{i}(:,kk-outputsToPlot),...
2082                         'Color',printCell{i,2}(kk).lineColor,...
2083                         'Linewidth',str2num(printCell{i,2}(kk).lineWidth),...
2084                         'LineStyle',printCell{i,2}(kk).lineStyle,...
2085                         'Marker',printCell{i,2}(kk).marker,...
2086                         'MarkerEdgeColor',printCell{i,2}(kk).edgeColor ,...
2087                         'MarkerFaceColor',printCell{i,2}(kk).faceColor);
2088                     stringMatrix{counterStringMatrix} = ['State ' num2str(kk-outputsToPlot) ' of node ' num2str(i)];
2089                 end
2090             end
2091             legend(stringMatrix,'Location','NorthEastOutside');
2092             xlabel('Simulation time in [s]');
2093             ylabel(['Output and/or state of node ' num2str(i)]);
2094
2095             hold off;
2096         end
2097     end
2098 end
2099 setappdata(handles.figure1,'appData',data);
2100
2101
2102
2103 % --------------------------------------------------------------------
2104 function plotAllOutput_Callback(hObject, eventdata, handles)
2105 % hObject    handle to plotAllOutput (see GCBO)
2106 % eventdata  reserved - to be defined in a future version of MATLAB
2107 % handles    structure with handles and user data (see GUIDATA)
2108 data = getappdata(handles.figure1,'appData');
2109
2110 if strcmp(get(handles.plotAllOutput,'Checked'),'on')
2111     set(handles.plotAllOutput,'Checked','off')
2112     plotAllOutput = 0;
2113 else
2114     set(handles.plotAllOutput,'Checked','on')
2115     plotAllOutput = 1;
2116 end
2117 %store application data
2118 data.plotAllOutput = plotAllOutput;
2119 setappdata(handles.figure1,'appData',data);
2120 guidata(hObject, handles);
2121
2122
2123 % --------------------------------------------------------------------
2124 function run_simulation_plots_Callback(hObject, eventdata, handles)
2125 % hObject    handle to run_simulation_plots (see GCBO)
2126 % eventdata  reserved - to be defined in a future version of MATLAB
2127 % handles    structure with handles and user data (see GUIDATA)
2128
2129 %load application data
2130 data = getappdata(handles.figure1,'appData');
2131 g = data.g;
2132 printCell = data.printCell;
2133 templates = s;
2134 expSucc = data.expSucc;
2135
2136 %global g;
2137 %global printCell;
2138 %global templates;
2139 %global expSucc;
2140 global xout;
2141 global tout;
2142
2143
2144 %After export to simulink is complete, start the simulation, using the
2145 %plotting parameters in printCell
2146 if expSucc ~= 1
2147     msgbox('Please start Export to Simulink2 before using this function.','Notice');
2148 end
2149
2150 if expSucc == 1
2151     %We need: number of nodes, number of internal states per node
2152     nrNodes = nv(g);
2153     intStates = zeros(nrNodes,1);
2154     for i = 1:nrNodes
2155         intStates(i) = length(printCell{i,1})-1;
2156     end
2157
2158     %t contains the simulation time, x the states in order of the nodenumbers.
2159     %The output of each %node is contained in the To Workspace struct nodeouti,
2160     %where i stands for the nodenumber
2161     %[t,x]=sim(gcs);
2162
2163     %Plotting of the simulation result can be done on different ways. For now,
2164     %every state gets its own figure
2165
2166     for i = 1:nrNodes
2167         %Check printCell to see if visualization of state i is wanted
2168         temp = printCell{i,1};
2169         if any(temp)
2170         figure;
2171         hold on;
2172         y = evalin('base',['nodeout' num2str(i) '.signals.values']);
2173         plot(tout,y,'Linewidth',2.0);
2174         %legend(['Output signal of node' num2str(i)]);
2175         xlabel('Simulation time in [s]');
2176
2177         if strcmp(templates{i},'LTI')
2178             if i == 1
2179                 index = 1;
2180             else
2181                 index = 1+sum(intStates(1:(i-1)));
2182             end
2183             x_loc = xout(:,index:index+intStates(i)-1);
2184             %Build string matrix for legend
2185             stringMatrix = cell(1,1);
2186             stringMatrix{1} = ['Output signal of node ' num2str(i)];
2187             counterStringMatrix = 1;
2188             for j=2:intStates(i)+1
2189                 if temp(j) == 1
2190                     counterStringMatrix = counterStringMatrix + 1;
2191                     stringMatrix = [stringMatrix; cell(1,1)];
2192                     p=plot(t,x_loc(:,j-1),'Linewidth',1.2);
2193                     R = 0.1 + 0.5*rand;
2194                     G = 0.1 + 0.5*rand;
2195                     B = 0.1 + 0.5*rand;
2196                     set(p,'Color', [R G B]);
2197                     stringMatrix{counterStringMatrix} = ['State ' num2str(j-1) ' of node ' num2str(i)];
2198                 end
2199             end
2200             legend(stringMatrix,'Location','NorthEastOutside');
2201         else
2202             legend(['Output signal of node ' num2str(i)]);
2203         end
2204         hold off;
2205         end
2206     end
2207 end
2208
2209 % --- Executes on button press in pushbutton17.
2210 % -- This button is only necessary for easily generating debugging output
2211 % -- it should be set to invisible or deleted after debugging
2212 function pushbutton17_Callback(hObject, eventdata, handles)
2213 % hObject    handle to pushbutton17 (see GCBO)
2214 % eventdata  reserved - to be defined in a future version of MATLAB
2215 % handles    structure with handles and user data (see GUIDATA)
2216       %DEBUGGING
2217 data = getappdata(handles.figure1,'appData');
2218 disp(['Number of nodes: ' num2str(nv(data.g)) ]);
2219 %disp(['PrintCell: ' printCell(nodenumber)]);
2220 assignin('base','data',data);
2221
2222 % --------------------------------------------------------------------
2223 function showSimMod_Callback(hObject, eventdata, handles) %#ok<*INUSL>
2224 % hObject    handle to showSimMod (see GCBO)
2225 % eventdata  reserved - to be defined in a future version of MATLAB
2226 % handles    structure with handles and user data (see GUIDATA)
2227 data = getappdata(handles.figure1,'appData');
2228 if strcmp(get(handles.showSimMod,'Checked'),'on')
2229     set(handles.showSimMod,'Checked','off')
2230     data.flag_showSimMod = 0;
2231 else
2232     set(handles.showSimMod,'Checked','on')
2233     data.flag_showSimMod = 1;
2234 end
2235 setappdata(handles.figure1,'appData',data);
2236 guidata(hObject, handles);
2237
2238
2239 function load_settings(filename,handles)
2240 %data = getappdata(handles.figure1,'appData');
2241 S=load(filename, 'modus','flag_showSimMod','plotAllOutput','template_list');
2242 data.modus = S.modus;
2243 data.flag_showSimMod = S.flag_showSimMod;
2244 data.plotAllOutput = S.plotAllOutput;
2245 data.template_list = S.template_list;
2246 setappdata(handles.figure1,'appData',data);
2247
2248 function save_settings(filename,handles)
2249 data = getappdata(handles.figure1,'appData');
2250 save(filename, '-struct','data', 'modus', 'flag_showSimMod','plotAllOutput',...
2251     'template_list');
2252
2253
2254 function loadGraphAtOpening(hObject, eventdata, handles)
2255 % hObject    handle to loadgraph (see GCBO)
2256 % eventdata  reserved - to be defined in a future version of MATLAB
2257 % handles    structure with handles and user data (see GUIDATA)
2258 data = getappdata(handles.figure1,'appData');
2259 template_list = data.template_list;
2260 filename = 'lastgraph.mat';
2261 pathname = [pwd filesep 'resources' filesep];
2262 if ~isempty(filename)
2263     file = strcat(pathname, filename);
2264     [pathname, filename, ext] = fileparts(file);
2265     if strcmp(ext, '.mat')
2266         S = load(file, 'nverts', 'nedges','adj_matrix', 'XY', 'labs', 'templates',...
2267             'printCell','template_list','modus','nodeColor') ;
2268         nverts = S.nverts;
2269         adj_matrix = S.adj_matrix;
2270         XY = S.XY;
2271         labs = S.labs;
2272         templates = S.templates;
2273         template_list = S.template_list;
2274         data.modus = S.modus;
2275         data.printCell = S.printCell;
2276         data.nodeColor = S.nodeColor;
2277         g = graph(nverts);
2278         switch data.modus;
2279             case 'undirected'; dir = 0;
2280             case 'directed'; dir = 1;
2281         end
2282         for i=1:nverts
2283             label(g,i,labs{i});
2284             for j=1:nverts
2285                 if adj_matrix(i,j)
2286                     add(g,i,j,dir);
2287                     adj_matrix(j,i) = 0;
2288                 end
2289             end
2290         end
2291         embed(g,XY);
2292     end
2293 end
2294 %set the uipanel according to stored value of "modus"
2295 switch data.modus
2296     case 'directed'
2297         set(handles.button_undirected,'Value', 0.0);
2298         set(handles.button_directed,'Value', 1.0);
2299     case 'undirected'
2300         set(handles.button_undirected,'Value', 1.0);
2301         set(handles.button_directed,'Value', 0.0);
2302 end
2303 %store application data
2304 data.g = g;
2305 data.templates = templates;
2306 data.template_list = template_list;
2307 setappdata(handles.figure1,'appData',data);
2308 guidata(hObject, handles);
2309
2310
2311 % --------------------------------------------------------------------
2312 function set_node_color_Callback(hObject, eventdata, handles)
2313 % hObject    handle to set_node_color (see GCBO)
2314 % eventdata  reserved - to be defined in a future version of MATLAB
2315 % handles    structure with handles and user data (see GUIDATA)
2316 data = getappdata(handles.figure1,'appData');
2317 temp = setnodecolor(data.template_list);
2318 if ~isempty(temp)
2319     data.template_list = temp;
2320     for i = 1:nv(data.g)
2321         nr_template = find(strcmp(data.templates(i), data.template_list(:,1)));
2322         data.nodeColor{i,1} = data.template_list{nr_template,2};
2323         data.nodeColor{i,2} = data.template_list{nr_template,3};
2324     end
2325 end
2326
2327 guidata(hObject, handles);
2328 setappdata(handles.figure1,'appData',data);
2329 refresh_graph(0, eventdata, handles,hObject);
2330
2331
2332 % --------------------------------------------------------------------
2333 function create_dynamic_Template_Callback(hObject, eventdata, handles)
2334 % hObject    handle to create_dynamic_Template (see GCBO)
2335 % eventdata  reserved - to be defined in a future version of MATLAB
2336 % handles    structure with handles and user data (see GUIDATA)
2337 % out = dialog('WindowStyle', 'normal', 'Name', 'Open');
2338 title = 'Creation of new dynamic template';
2339 message = ['A new model in Simulink will be loaded now. Please leave Inport, Outport, ' ...
2340     'the Mux-Block at the Inport and the ''To Workspace''-Block unmodified. Save ',...
2341     'your work afterwards and open the import ' ...
2342     'wizard to use the created dynamics in mtids.' ...
2343     'See ''help'' for detailed advise.'];
2344 h1=msgbox(message,title,'help');
2345 posVector=get(h1,'OuterPosition');
2346 set(h1,'OuterPosition',posVector + [0 0 20 0]); %[left, bottom, width, height]
2347 simulink;
2348 open_system('nodeTemplate.mdl');
2349
2350
2351
2352 % --------------------------------------------------------------------
2353 function template_import_wizard_Callback(hObject, eventdata, handles)
2354 % hObject    handle to template_import_wizard (see GCBO)
2355 % eventdata  reserved - to be defined in a future version of MATLAB
2356 % handles    structure with handles and user data (see GUIDATA)
2357
2358 % next step: load template invisibly from mdl-file
2359 oldFolder = cd(strcat(pwd,'/templates'));
2360
2361 [filename, pathname] = uigetfile(...
2362 {'*.mdl','Simulink model template(*.mdl)';
2363    '*.*',  'All Files (*.*)'}, ...
2364    'Import Simulink model templates', ...
2365    'MultiSelect', 'on');
2366
2367 % disp(['Filename: ' filename]);
2368 if all(filename ~= 0)
2369     load_system(filename);
2370 else
2371     cd(oldFolder);
2372     return
2373 end
2374
2375 % check this file for unset parameter values - this is a prestep to the
2376 % dialog of asking for all needed parameters for this template
2377 % finds all blocks in the simulink model
2378 blks = find_system(gcs, 'Type', 'block');
2379 listblks = get_param(blks, 'BlockType');
2380 listnms = get_param(blks,'Name');
2381
2382 % is is very hard to show the variation of all editable parameters
2383 % thus just show the blocks and let the user type in which values should be
2384 % introduced as parameters for the template OR make a choice of possible
2385 % values, which are very likely
2386
2387 % there are some blocks, which are very likely not to contain parameters,
2388 % which the user should set, e.g.:
2389 % Inport, Outport, Sum, Mux, Math
2390 % sort out these blocks:
2391 listnms(~cellfun(@isempty, regexp(listblks,...
2392     'Inport|Outport|Sum|Mux|Math|Scope|ToWorkspace','start'))) = [];
2393 listblks(~cellfun(@isempty, regexp(listblks,...
2394     'Inport|Outport|Sum|Mux|Math|Scope|ToWorkspace','start'))) = [];
2395
2396 % create new figure and place found blocks in table environment
2397 if ~cellfun(@isempty, listblks)
2398     argout = import_dynamic_params(listblks,listnms,filename,pathname); %#ok<NASGU>
2399 else
2400     % errordlg('No blocks with editable');
2401 end
2402
2403 close_system(filename,0);
2404 cd(oldFolder);
2405 data = getappdata(handles.figure1,'appData');
2406 data.template_list = readImportedTemplates(data.template_list);
2407 setappdata(handles.figure1,'appData',data);
2408 refresh_dynamics(eventdata, handles);
2409
2410 % --------------------------------------------------------------------
2411 function saveGraph(hObject, eventdata, handles, pathname, filename)
2412 % hObject    handle to savegraphas (see GCBO)
2413 % eventdata  reserved - to be defined in a future version of MATLAB
2414 % handles    structure with handles and user data (see GUIDATA)
2415
2416 %load application data
2417 data = getappdata(handles.figure1,'appData');
2418 g = data.g;
2419 templates = data.templates;
2420 template_list = data.template_list;
2421 modus = data.modus;
2422 printCell = data.printCell;
2423
2424 if filename
2425      file = strcat(pathname, filename);
2426      [pathname, filename, ext] = fileparts(file);
2427      %save(g, file);
2428
2429      adj_matrix = double(matrix(g));
2430      labs = get_label(g);
2431      XY = getxy(g);
2432      nverts = nv(g);
2433      nedges = ne(g);
2434      nodeColor = data.nodeColor;
2435
2436      if strcmp(ext, '.mat')
2437         %save(file, 'data');
2438         save(file, 'nverts', 'nedges','adj_matrix', 'XY', 'labs', 'templates',...
2439             'printCell','template_list','modus','nodeColor') ;
2440 %         disp(strcat('Saved graph as binary .mat file ("', file,'")'));
2441      elseif strcmp(ext, '.gr')
2442         save(g, file);
2443         disp(strcat('Saved graph as Matgraph file ("', file,'")'));
2444      end
2445 end
2446 refresh_graph(0, eventdata, handles,hObject);
2447
2448 % --------------------------------------------------------------------
2449 function menu_manageParamSets_Callback(hObject, eventdata, handles)
2450 % hObject    handle to menu_manageParamSets (see GCBO)
2451 % eventdata  reserved - to be defined in a future version of MATLAB
2452 % handles    structure with handles and user data (see GUIDATA)
2453 data = getappdata(handles.figure1,'appData');
2454 manageParamSets(readImportedTemplates(data.template_list));
2455 data.template_list = readImportedTemplates(data.template_list);
2456 setappdata(handles.figure1,'appData',data);
2457 refresh_dynamics([], handles);
2458
2459 % --------------------------------------------------------------------
2460 function get_simParams_Callback(hObject, eventdata, handles)
2461 % hObject    handle to get_simParams (see GCBO)
2462 % eventdata  reserved - to be defined in a future version of MATLAB
2463 % handles    structure with handles and user data (see GUIDATA)
2464 data = getappdata(handles.figure1,'appData');
2465 % sysname means the name of an arbitrary template, which is used in mtids.
2466 % it's just for getting a configuration set for simulink out of it
2467 sysname = [data.template_list{1,1} '_CHECKED'];
2468 if isfield(data,'simPrms')
2469     oldPrms = data.simPrms;
2470 else
2471     oldPrms = [];
2472 end
2473 data.simPrms = editSimParams(sysname,oldPrms);
2474 setappdata(handles.figure1,'appData',data);
2475
2476 %--------------------------------------------------------------------------
2477 %-------UNUSED FUNCTION CALLBACKS - AUTOMATICALLY GENERATED BY GUIDE-------
2478 %--------------------------------------------------------------------------
2479
2480 function radiobutton7_Callback(hObject, eventdata, handles)
2481
2482 function tonode_Callback(hObject, eventdata, handles)
2483
2484 function fromnode_Callback(hObject, eventdata, handles)
2485
2486 function Untitled_10_Callback(hObject, eventdata, handles)
2487
2488 function file_Callback(hObject, eventdata, handles)
2489
2490 function Untitled_9_Callback(hObject, eventdata, handles)
2491
2492 function Untitled_11_Callback(hObject, eventdata, handles)
2493
2494 function generatesimulinkmdl_Callback(hObject, eventdata, handles)
2495
2496 function Untitled_12_Callback(hObject, eventdata, handles)
2497
2498 function figure1_ResizeFcn(hObject, eventdata, handles)
2499
2500 function listbox1_Callback(hObject, eventdata, handles)
2501
2502 function about_Callback(hObject, eventdata, handles)
2503
2504 function adddynamics_Callback(hObject, eventdata, handles)
2505
2506 function dynamicsimporter_Callback(hObject, eventdata, handles)
2507
2508 function checkbox2_Callback(hObject, eventdata, handles)
2509
2510 function figure1_KeyPressFcn(hObject, eventdata, handles)
2511
2512 function Savegraph_Callback(hObject, eventdata, handles)
2513
2514 function Untitled_17_Callback(hObject, eventdata, handles)
2515
2516 function viewmenu_Callback(hObject, eventdata, handles)
2517
2518 function editnode_Callback(hObject, eventdata, handles)
2519
2520 function Untitled_13_Callback(hObject, eventdata, handles)
2521
2522 function Untitled_14_Callback(hObject, eventdata, handles)
2523
2524 function click_add_node_long_Callback(hObject, eventdata, handles)
2525
2526 function remnode_Callback(hObject, eventdata, handles)
2527
2528 function dynamic_label_Callback(hObject, eventdata, handles)
2529
2530 function number_of_nodes_Callback(hObject, eventdata, handles)
2531
2532 function selector_valueSet_Callback(hObject, eventdata, handles) %#ok<*DEFNU,*INUSD>
2533
2534
2535 %%%%%%%%%
2536